In [1]:
import torch 

float32_tensor = torch.tensor([1.0,2.0,3.0], dtype=torch.float32)
float64_tensor = torch.tensor([1.0,2.0,3.0], dtype=torch.float64)
float16_tensor = torch.tensor([1.0,2.0,3.0],dtype=torch.float16)
bfloat16_tensor = torch.tensor([1.0,2.0,3.0], dtype=torch.bfloat16)
complex32_tensor = torch.tensor([1 + 2j, 3 + 4j], dtype=torch.complex32)
complex64_tensor = torch.tensor([1 + 2j, 3 + 4j], dtype= torch.complex64)
complex128_tensor = torch.tensor([1 + 2j, 3 + 4j], dtype= torch.complex128)
uint8_tensor = torch.tensor([1,2,3],dtype=torch.uint8)
uint16_tensor = torch.tensor([1,2,3], dtype=torch.uint16)
uint32_tensor = torch.tensor([1,2,3], dtype=torch.uint32)
uint64_tensor = torch.tensor([1,2,3], dtype=torch.uint64)
int8_tensor = torch.tensor([1,2,3],dtype=torch.int8)
int16_tensor = torch.tensor([1,2,3], dtype=torch.int16)
int32_tensor = torch.tensor([1,2,3], dtype=torch.int32)
int64_tensor = torch.tensor([1,2,3], dtype=torch.int64)
bool_tensor = torch.tensor([True, False , True], dtype=torch.bool)
quint8_tensor = torch.quantize_per_tensor(torch.tensor([1.0,2.0,3.0]), scale=1.0, zero_point=0, dtype=torch.quint8)
qint8_tensor = torch.quantize_per_tensor(torch.tensor([1.0,2.0,3.0]), scale=1.0, zero_point=0, dtype=torch.qint8)
qint32_tensor = torch.quantize_per_tensor(torch.tensor([1.0,2.0,3.0]), scale=1.0, zero_point=0, dtype=torch.qint32)
quint4x2_tensor = torch.quantize_per_tensor(torch.tensor([1.0,2.0,3.0]), scale=1.0, zero_point=0, dtype= torch.quint4x2)

# if hasattr(torch, 'float8_e4m3fn'):
    # float8_e43fn_tensor = torch.tensor([1.0,2.0,3.0], dtype=torch.float8_e43fn)
if hasattr(torch, 'float8_e5m2'):
    float8_e5m2_tensor = torch.tensor([1.0,2.0,3.0], dtype=torch.float8_e5m2)


print("32-bit floating point (torch.float32):", float32_tensor)
print("64-bit floating point (torch.float64):", float64_tensor)
print("16-bit floating point (torch.float16):", float16_tensor)
print("16-bit brain floating point (torch.bfloat16):", bfloat16_tensor)
print("32-bit complex (torch.complex32):", complex32_tensor)
print("64-bit complex (torch.complex64):", complex64_tensor)
print("128-bit complex (torch.complex128):", complex128_tensor)
print("8-bit integer (unsigned) (torch.uint8):", uint8_tensor)
print("16-bit integer (signed) (torch.int16):", uint16_tensor)
print("32-bit integer (signed) (torch.int32):", uint32_tensor)
print("64-bit integer (signed) (torch.int64):", uint64_tensor)
print("8-bit integer (signed) (torch.int8):", int8_tensor)
print("16-bit integer (signed) (torch.int16):", int16_tensor)
print("32-bit integer (signed) (torch.int32):", int32_tensor)
print("64-bit integer (signed) (torch.int64):", int64_tensor)
print("Boolean (torch.bool):", bool_tensor)
print("Quantized 8-bit integer (unsigned) (torch.quint8):", quint8_tensor)
print("Quantized 8-bit integer (signed) (torch.qint8):", qint8_tensor)
print("Quantized 32-bit integer (signed) (torch.qint32):", qint32_tensor)
print("Quantized 4-bit integer (unsigned) (torch.quint4x2):", quint4x2_tensor)
print("8-bit floating point, e5m2 (torch.float8_e5m2):", float8_e5m2_tensor)


32-bit floating point (torch.float32): tensor([1., 2., 3.])
64-bit floating point (torch.float64): tensor([1., 2., 3.], dtype=torch.float64)
16-bit floating point (torch.float16): tensor([1., 2., 3.], dtype=torch.float16)
16-bit brain floating point (torch.bfloat16): tensor([1., 2., 3.], dtype=torch.bfloat16)
32-bit complex (torch.complex32): tensor([1.+2.j, 3.+4.j], dtype=torch.complex32)
64-bit complex (torch.complex64): tensor([1.+2.j, 3.+4.j])
128-bit complex (torch.complex128): tensor([1.+2.j, 3.+4.j], dtype=torch.complex128)
8-bit integer (unsigned) (torch.uint8): tensor([1, 2, 3], dtype=torch.uint8)
16-bit integer (signed) (torch.int16): tensor([1, 2, 3], dtype=torch.uint16)
32-bit integer (signed) (torch.int32): tensor([1, 2, 3], dtype=torch.uint32)
64-bit integer (signed) (torch.int64): tensor([1, 2, 3], dtype=torch.uint64)
8-bit integer (signed) (torch.int8): tensor([1, 2, 3], dtype=torch.int8)
16-bit integer (signed) (torch.int16): tensor([1, 2, 3], dtype=torch.int16)
32-bit

C:\Users\fadzw\AppData\Local\Temp\ipykernel_18756\2747244299.py:7: UserWarning: ComplexHalf support is experimental and many operators don't support it yet. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\EmptyTensor.cpp:51.)
  complex32_tensor = torch.tensor([1 + 2j, 3 + 4j], dtype=torch.complex32)


In [1]:
#Tensor.new_tensor

import torch 

base_tensor = torch.ones((2,), dtype=torch.int8)
print('base tensor:',base_tensor)

data = [[0,1],[2,3]]
#same dtype and device as the base tensor
new_tensor_default = base_tensor.new_tensor(data)
print('\nnew tensor (default):', new_tensor_default)

#specify a different dtype
new_tensor_float32 = base_tensor.new_tensor(data,dtype=torch.float32)
print('\nnew tensor (dtype=torch.float32):',new_tensor_float32)

#specify a different device
if torch.cuda.is_available():
    new_tensr_cuda = base_tensor.new_tensor(data, device='cuda')
    print('\n new tensor (device=cuda):',new_tensor_cuda)
else:
    print('\ncuda is not available. skipping GPU example')


#specify requier_grad=True for autograd tracking
new_tensor_requires_grad = base_tensor.new_tensor(data,dtype=torch.float32, requires_grad=True)
print('\n new tensor (requires_grad)=True:',new_tensor_requires_grad)

#perform a dummy operation to demonstrate autograd
output = new_tensor_requires_grad.sum()
output.backward()
print('Gradient of New Tensor:',new_tensor_requires_grad.grad)

#specify layout (default is torch.strided)
# new_tensor_strided = base_tensor.new_tensor(data, layout=torch.strided)
# print('\n new tensor (layout=torch.strided):',new_tensor_strided)

#specify pin_memory=True (only works for CPU tensors)
# new_tensor_pinned = base_tensor.new_tensor(data, pin_memory=True)
# print('\n new tensor (pin_memory=True):',new_tensor_pinned)

# Alternative for pin_memory=True (only works for CPU tensors)
# pinned_tensor = torch.tensor(data, dtype=torch.int8).pin_memory() #RuntimeError: Cannot access accelerator device when none is available.
# print("\nPinned Tensor (pin_memory=True):", pinned_tensor)


# Alternative for sparse layout
indices = torch.tensor([[0, 1], [1, 0]])
values = torch.tensor([3, 4], dtype=torch.float32)
sparse_tensor = torch.sparse_coo_tensor(indices, values, size=(2, 2))
print("\nSparse Tensor (layout=torch.sparse_coo):", sparse_tensor)

base tensor: tensor([1, 1], dtype=torch.int8)

new tensor (default): tensor([[0, 1],
        [2, 3]], dtype=torch.int8)

new tensor (dtype=torch.float32): tensor([[0., 1.],
        [2., 3.]])

cuda is not available. skipping GPU example

 new tensor (requires_grad)=True: tensor([[0., 1.],
        [2., 3.]], requires_grad=True)
Gradient of New Tensor: tensor([[1., 1.],
        [1., 1.]])

Sparse Tensor (layout=torch.sparse_coo): tensor(indices=tensor([[0, 1],
                       [1, 0]]),
       values=tensor([3., 4.]),
       size=(2, 2), nnz=2, layout=torch.sparse_coo)


In [2]:
#Tensor.new_full

# creates a tensor for a spcified size filled with a given value and inherits properties like dtype and devvice from the original tensor unless overridden

import torch 

tensor = torch.ones((2,), dtype=torch.float64)

print('original tensor:')
print(tensor)
print('dtype:',tensor.dtype)
print('device',tensor.device)

#create a new tensor for size 3 4 filled with 3.141592
new_tensor = tensor.new_full((3,4),3.141592)

print('\n new tensor (inherits dtype and device from original)')
print(new_tensor)
print('dtype:',new_tensor.dtype)
print('device:',new_tensor.device)

#create a new tensor on a different device and dtype
if torch.cuda.is_available():
    new_tensor_gpu = tensor.new_full(
        size=(2,3),
        fill_value=2.718,
        dtype=torch.float32,
        device='cuda'
    )
    print('\nenw tensor on GPU with dtype = torch.float32')
    print(new_tensor_gpu)
    print('dtype:',new_tensor_gpu.dtype)
    print('device:',new_tensor_gpu.device)
else:
    print('\nCUDA is not available. Skipping GPU tensor creation.')

original tensor:
tensor([1., 1.], dtype=torch.float64)
dtype: torch.float64
device cpu

 new tensor (inherits dtype and device from original)
tensor([[3.1416, 3.1416, 3.1416, 3.1416],
        [3.1416, 3.1416, 3.1416, 3.1416],
        [3.1416, 3.1416, 3.1416, 3.1416]], dtype=torch.float64)
dtype: torch.float64
device: cpu

CUDA is not available. Skipping GPU tensor creation.


In [3]:
#Tensor.new_empty

# creates a new tensor of a specified size, filled with uninitialized data. 
# the new tensor inherits properties like dtype and device from the original tensor unless overridden

import torch 

tensor = torch.ones((2,),dtype=torch.float64)

print('original tensor:')
print(tensor)
print('dtype:',tensor.dtype)
print('device:', tensor.device)

new_tensor = tensor.new_empty((3,4))

print('\n new empty tensor (inherits dtype and device from original):')
print(new_tensor)
print('dtype:', new_tensor.dtype)
print('device:', new_tensor.device)

#create a new empty tensor on a different device
if torch.cuda.is_available():
    new_tensor_gpu = tensor.new_empty(
        size=(2,3),
        dtype=torch.float32,
        device ='cuda'
    )
    print('\n new empty tensor on GPU with dtype=torch.float32')
    print(new_tensor_gpu)
    print('dtype:', new_tensor_gpu.dtype)
    print('dtype:', new_tensor_gpu.device)
else:
    print('\nCUDA is not available . Skipping GPU tensor creation')

original tensor:
tensor([1., 1.], dtype=torch.float64)
dtype: torch.float64
device: cpu

 new empty tensor (inherits dtype and device from original):
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]], dtype=torch.float64)
dtype: torch.float64
device: cpu

CUDA is not available . Skipping GPU tensor creation


In [4]:
#Tensor.new_ones

# creates a new tensor of a specified size, fillwd with ones.  THe new tensor inherits properties like dtype an device from the orignal tensor uness overridden

import torch 
tensor = torch.tensor((),dtype=torch.int32)

print('original tensor:')
print(tensor)
print('dtype:',tensor.dtype)
print('device:',tensor.device)

#filled with ones
new_tensor = tensor.new_ones((2,3))
print('\n nre tensosr filled with ones (inherits dtype and device from original:)')
print(new_tensor)
print('dtype:',new_tensor.dtype)

print('device:',new_tensor.device)

# create a tensor on a different device and a dtype
if torch.cuda.is_available():
    new_tensor_gpu = tensor.new_ones(
        size=(3,2),
        dtype=torch.float32,
        devicee='cuda'
    )
    print('\nNew tensor filled with ones on GPU with dtype=torch.float32')
    print(new_tensor_gpu)
    print('dtype:',new_tensor_gpu.dtype)
    print('device:',new_tensor_gpu.device)
else:
    print('\n CUDA is not available . Skipping GPU tensor creation')

original tensor:
tensor([], dtype=torch.int32)
dtype: torch.int32
device: cpu

 nre tensosr filled with ones (inherits dtype and device from original:)
tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)
dtype: torch.int32
device: cpu

 CUDA is not available . Skipping GPU tensor creation


In [6]:
#Tensor.new_zeros

# creates a new tensor of a specified size, fillwd with ones.  THe new tensor inherits properties like dtype an device from the orignal tensor uness overridden

import torch 
tensor = torch.tensor((),dtype=torch.int32)

print('original tensor:')
print(tensor)
print('dtype:',tensor.dtype)
print('device:',tensor.device)

#filled with ones
new_tensor = tensor.new_zeros((2,3))
print('\n nre tensosr filled with ones (inherits dtype and device from original:)')
print(new_tensor)
print('dtype:',new_tensor.dtype)

print('device:',new_tensor.device)

# create a tensor on a different device and a dtype
if torch.cuda.is_available():
    new_tensor_gpu = tensor.new_zeros(
        size=(3,2),
        dtype=torch.float32,
        devicee='cuda'
    )
    print('\nNew tensor filled with ones on GPU with dtype=torch.float32')
    print(new_tensor_gpu)
    print('dtype:',new_tensor_gpu.dtype)
    print('device:',new_tensor_gpu.device)
else:
    print('\n CUDA is not available . Skipping GPU tensor creation')

#Tensor.is_cuda
# is True if the Tensor is sotred on the GPU False otherwise

original tensor:
tensor([], dtype=torch.int32)
dtype: torch.int32
device: cpu

 nre tensosr filled with ones (inherits dtype and device from original:)
tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)
dtype: torch.int32
device: cpu

 CUDA is not available . Skipping GPU tensor creation


In [8]:
#Tnesor.is_quqntized

#property checks whether a tensor is quantized or not.
# quantized tensors are sued in pytoch for low-precision computations , typically in scenarios like model optimmization for deployment on resrouce-contrained devices.

import torch 
float_tensor = torch.tensor([1.0,2.0,3.0], dtype=torch.float32)

print('is float_tensor quantized?')
print(float_tensor.is_quantized)

quantized_tensor = torch.quantize_per_tensor(
    float_tensor, scale=0.1, zero_point=0, dtype=torch.quint8
)

#check if tensor is quantized
print('\nis quantized_tensor quantized?')
print(quantized_tensor.is_quantized)

# print details of the quantized tensor
print('\n tensor details')
print(quantized_tensor)
print('scale', quantized_tensor.q_scale())
print('zero point:', quantized_tensor.q_zero_point())
print('dtype',quantized_tensor.dtype)

is float_tensor quantized?
False

is quantized_tensor quantized?
True

 tensor details
tensor([1., 2., 3.], size=(3,), dtype=torch.quint8,
       quantization_scheme=torch.per_tensor_affine, scale=0.1, zero_point=0)
scale 0.1
zero point: 0
dtype torch.quint8


In [10]:
#Tensor.is_meta

# this property checks whether a tensor is a meta tensor
# meta tensors are special tensors that do not allocate memory for their data and are used primarlyy for shape and metadata inference without storing actual values

import torch 

regular_tensor = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float32)
print('si regular_tensor a meta tensor?')
print(regular_tensor.is_meta)

meta_tensor = torch.empty(3, dtype=torch.float32, device='meta')
print('\n is meta_tenosr a meta tensor?')
print(meta_tensor.is_meta)

print# Print details of the meta tensor
print("\nMeta Tensor Details:")
print("Shape:", meta_tensor.shape)
print("Dtype:", meta_tensor.dtype)
print("Device:", meta_tensor.device)

# Attempt to access data from the meta tensor (will raise an error)
try:
    print("\nAccessing data from meta_tensor:")
    print(meta_tensor[0])  # This will raise an error
except RuntimeError as e:
    print("Error:", e)

si regular_tensor a meta tensor?
False

 is meta_tenosr a meta tensor?
True

Meta Tensor Details:
Shape: torch.Size([3])
Dtype: torch.float32
Device: meta

Accessing data from meta_tensor:
tensor(..., device='meta', size=())


* `torch.Tensor.device` returns torch.device object associated with tensor. this indicates whether tensro resides on the CPU or specific GPU. the device property of a tenspr tells where the tensor is located. operations between tensors on different devices will raise errors. by default tensors are created on the CPU unless explicityly moved to a GPU.
    * `torch.device('cpu')` indicates the tensor is on the CPU.
    * `torch.device('cuda:0')` indicates the tensor is on the first GPU.
* `torch.Tensor.grad` stores gradient computed during backpropagation for a tensor that requires gradient tracking (requires_grad=True). Initially it is None and it gets populated after calling `backward()`.
    * grad attribute
        * is None by default
        * become a tensor containing gradients after backward() called on a scalar loss or output tensor.
        * accumulates a gradients if `backward()` is called multiple times (unless explicityly zeroed out using zero())
    * to track gradients for a tensor
        * set `requires_grad=True` when creating the tensor
        * gradients are computed only for tensors involved in operations that require gradient computation
        * when you call z.backwards() multiple times without resetting the computational graph , pytorcj will raise a runtime error. this happens because pytorch clears the intermediate vaules fo the comptational graph after the first call backward().
            * these intermediate values are neceassary for a gradient computation, so attemptinig to compute gadients again without rebuilding the graph will fail
* `torch.Tensor.ndim` is an alias for dim(). returns the number of dimensions of a tensor. scalar ndim 0 , vector ndim 1 matrix ndim 2
* `torch.Tensor.real` extracts the real part of a complex-values tensor. if tensor is real-valued it simplyy returns the tensor itslef. data type like torch.cflaot and torch.cdouble will be removed and returns a new tensor containing only the real parts
* `torch.Tensor.imag` extracts the imaginary part of a complex-valued tensor. it is only supported for tensor with complex data types

In [1]:
import torch

# Create a tensor on the CPU
cpu_tensor = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float32)

# Check the device of the CPU tensor
print("CPU Tensor Device:")
print(cpu_tensor.device)  # Output: cpu

# Check if CUDA is available
if torch.cuda.is_available():
    # Move the tensor to the GPU (default GPU: cuda:0)
    gpu_tensor = cpu_tensor.to("cuda")
    
    # Check the device of the GPU tensor
    print("\nGPU Tensor Device:")
    print(gpu_tensor.device)  # Output: cuda:0
    
    # Move the tensor back to the CPU
    cpu_tensor_again = gpu_tensor.to("cpu")
    
    # Check the device after moving back to the CPU
    print("\nMoved Back to CPU Tensor Device:")
    print(cpu_tensor_again.device)  # Output: cpu
else:
    print("\nCUDA is not available. Skipping GPU-related operations.")

CPU Tensor Device:
cpu

CUDA is not available. Skipping GPU-related operations.


In [3]:
import torch

# Create a tensor with requires_grad=True to track gradients
x = torch.tensor([2.0, 3.0, 4.0], requires_grad=True)

# Define a function y = x^2 + 3x + 5
y = x**2 + 3*x + 5

# Compute the sum of y (scalar value) to allow backward()
z = y.sum()

# Before calling backward(), grad is None
print("Gradient before backward():")
print(x.grad)  # Output: None

# Perform backpropagation to compute gradients
z.backward()

# After calling backward(), grad contains the computed gradients
print("\nGradient after backward():")
print(x.grad)  # Output: [11., 13., 15.]

# Recompute y and z to rebuild the computational graph
y = x**2 + 3*x + 5
z = y.sum()

# Call backward() again without zeroing gradients (gradients accumulate)
z.backward()

print("\nGradient after second backward() call (accumulated):")
print(x.grad)  # Output: [22., 26., 30.] (doubled due to accumulation)

# Zero out the gradients to reset them
x.grad.zero_()

print("\nGradient after zeroing:")
print(x.grad)  # Output: [0., 0., 0.]

Gradient before backward():
None

Gradient after backward():
tensor([ 7.,  9., 11.])

Gradient after second backward() call (accumulated):
tensor([14., 18., 22.])

Gradient after zeroing:
tensor([0., 0., 0.])


In [4]:
import torch

# Create a scalar tensor
scalar = torch.tensor(42)
print("Scalar Tensor:")
print("Value:", scalar)
print("Number of Dimensions (ndim):", scalar.ndim)  # Output: 0
print()

# Create a 1D tensor (vector)
vector = torch.tensor([1, 2, 3, 4])
print("1D Tensor (Vector):")
print("Shape:", vector.shape)
print("Number of Dimensions (ndim):", vector.ndim)  # Output: 1
print()

# Create a 2D tensor (matrix)
matrix = torch.tensor([[1, 2], [3, 4]])
print("2D Tensor (Matrix):")
print("Shape:", matrix.shape)
print("Number of Dimensions (ndim):", matrix.ndim)  # Output: 2
print()

# Create a 3D tensor
tensor_3d = torch.ones((2, 3, 4))
print("3D Tensor:")
print("Shape:", tensor_3d.shape)
print("Number of Dimensions (ndim):", tensor_3d.ndim)  # Output: 3
print()

# Create a 4D tensor (e.g., batch of images)
tensor_4d = torch.randn((8, 3, 64, 64))  # Batch size=8, Channels=3, Height=64, Width=64
print("4D Tensor (Batch of Images):")
print("Shape:", tensor_4d.shape)
print("Number of Dimensions (ndim):", tensor_4d.ndim)  # Output: 4

Scalar Tensor:
Value: tensor(42)
Number of Dimensions (ndim): 0

1D Tensor (Vector):
Shape: torch.Size([4])
Number of Dimensions (ndim): 1

2D Tensor (Matrix):
Shape: torch.Size([2, 2])
Number of Dimensions (ndim): 2

3D Tensor:
Shape: torch.Size([2, 3, 4])
Number of Dimensions (ndim): 3

4D Tensor (Batch of Images):
Shape: torch.Size([8, 3, 64, 64])
Number of Dimensions (ndim): 4


In [5]:
import torch

# Create a complex-valued tensor
x = torch.randn(4, dtype=torch.cfloat)  # Random complex numbers
print("Complex Tensor:")
print(x)

# Extract the real part of the tensor
real_part = x.real
print("\nReal Part of the Tensor:")
print(real_part)

# Verify that the real part is a real-valued tensor
print("\nIs the real part a real-valued tensor?")
print(real_part.is_complex())  # Output: False

# Create a real-valued tensor
y = torch.tensor([1.0, 2.0, 3.0, 4.0])
print("\nReal-Valued Tensor:")
print(y)

# Access the real property of a real-valued tensor
real_y = y.real
print("\nReal Part of a Real-Valued Tensor:")
print(real_y)

Complex Tensor:
tensor([ 0.4002-0.7091j, -0.8971-0.4174j, -0.6482+0.7085j, -0.6612+1.0229j])

Real Part of the Tensor:
tensor([ 0.4002, -0.8971, -0.6482, -0.6612])

Is the real part a real-valued tensor?
False

Real-Valued Tensor:
tensor([1., 2., 3., 4.])

Real Part of a Real-Valued Tensor:
tensor([1., 2., 3., 4.])


In [1]:
import torch

# Create a complex-valued tensor
x = torch.randn(4, dtype=torch.cfloat)  # Random complex numbers
print("Complex Tensor:")
print(x)

# Extract the imaginary part of the tensor
imaginary_part = x.imag
print("\nImaginary Part of the Tensor:")
print(imaginary_part)

# Verify that the imaginary part is a real-valued tensor
print("\nIs the imaginary part a real-valued tensor?")
print(imaginary_part.is_complex())  # Output: False

# Attempt to access the imaginary part of a real-valued tensor
y = torch.tensor([1.0, 2.0, 3.0, 4.0])
print("\nReal-Valued Tensor:")
print(y)

try:
    print("\nAttempting to access the imaginary part of a real-valued tensor:")
    print(y.imag)
except RuntimeError as e:
    print("Error:", e)

Complex Tensor:
tensor([-0.0473+0.2480j,  0.5865-1.1128j,  1.0534+0.5260j,  0.0574+0.0012j])

Imaginary Part of the Tensor:
tensor([ 0.2480, -1.1128,  0.5260,  0.0012])

Is the imaginary part a real-valued tensor?
False

Real-Valued Tensor:
tensor([1., 2., 3., 4.])

Attempting to access the imaginary part of a real-valued tensor:
Error: imag is not implemented for tensors with non-complex dtypes.


* `torch.Tensor.nbytes` returns a the total number of bytes consumed by the tensor's elements. It is calculated as 
    * nbytes = numberl() x element_size()
    * nummel, gives number of elements in the tensor
    * elements_size() gives the size of each element in the tensor
    * computes the memory usage of the tensor's data in bytes
    * only applies to tensors that do not use sparse storage layouts
    * useful for understanding the memory footprint of tensors, especially when working with large models or datasets
* `torch.Tensor.itemsize` property is an alias for element_size() it returns the size (in bytes) of a single element in the tensor
* `torch.Tensor.abs` computes the element-wise absolute value of a tensor equivalent with ``
* `torch.Tensor.acos()` alias `arccos()` computes inverse cosine (arccosine of a tensor) 
    * input values must ie in the range [-1,1] because the csine function output is bounded withing this range
    * the output values are in radioans and lie in the range [0,pi]
    * use for trigonometric clasculations of transofmations where you need to computes angles from cosine.

In [6]:
import torch 

int_tensor = torch.tensor([[1,2,3],[4,5,6]], dtype=torch.int32)
print('integer tensor:')
print(int_tensor)
print('number of elements (numel):',int_tensor.numel())
print('element size(bytes):', int_tensor.element_size())
print('total bytes consumed (nbytes):',int_tensor.nbytes)

float_tensor = torch.tensor([[1.0,2.0,3.0],[4.0,5.0,6.0]],dtype=torch.float64)
print('float tensor:')
print(float_tensor)
print('number of elements (numel):',float_tensor.numel())
print('element size (bytes):',float_tensor.element_size())
print('total bytes consumed (nbytes):',float_tensor.nbytes)

high_dim_tensor = torch.randn(2,3,4,dtype=torch.float32)
print('high-dimensional tensor:')
print(high_dim_tensor)
print('element size (bytes):',high_dim_tensor.element_size())
print('total bytes consumed (nbytes):',high_dim_tensor.nbytes)


integer tensor:
tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)
number of elements (numel): 6
element size(bytes): 4
total bytes consumed (nbytes): 24
float tensor:
tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)
number of elements (numel): 6
element size (bytes): 8
total bytes consumed (nbytes): 48
high-dimensional tensor:
tensor([[[ 2.0215, -0.3570, -1.9166, -0.5851],
         [-0.6711, -0.8350,  0.8931, -0.6189],
         [ 0.9530, -1.2006, -1.9954, -0.5458]],

        [[ 0.5730, -2.1895,  0.8464,  1.1774],
         [ 0.6392, -0.5943, -0.3627,  1.6737],
         [-0.7921,  0.3601, -0.4904, -0.5312]]])
element size (bytes): 4
total bytes consumed (nbytes): 96


In [1]:
import torch 

int_tensor = torch.tensor([1,2,3], dtype=torch.int32)
float32_tensor = torch.tensor([1.0,2.0,3.0], dtype=torch.float32)
float64_tensor = torch.tensor([1,2,3], dtype=torch.float64)
uint8_tensor = torch.tensor([1,2,3], dtype=torch.uint8)

print(int_tensor.itemsize)
print(float32_tensor.itemsize)
print(float64_tensor.itemsize)
print(uint8_tensor.itemsize)

4
4
8
1


In [9]:
import torch

real_tensor = torch.tensor([-3.0, 4.0, -5.0, 6.0])
abs_real_tensor = real_tensor.abs()
complex_tensor = torch.tensor([3 + 4j, -1 - 1j, 0 + 2j], dtype=torch.cfloat)
abs_complex_tensor = complex_tensor.abs()
print(real_tensor)
print(abs_real_tensor)
print(complex_tensor)
print(abs_complex_tensor)

tensor([-3.,  4., -5.,  6.])
tensor([3., 4., 5., 6.])
tensor([ 3.+4.j, -1.-1.j,  0.+2.j])
tensor([5.0000, 1.4142, 2.0000])


In [1]:
#  Cosine Similarity for Recommendation Systems
# Physics Simulartion
# Geospatial Data Analysis
# Quantum Computing Simulations
# Signal Processing
import torch 

user1_embedding = torch.tensor([0.5,0.5,0.7071])
user2_embedding = torch.tensor([0.7071, 0.7071, 0.0])

# compute cosine similarity
cosine_similarity = torch.dot(user1_embedding, user2_embedding)
angular_distance_radians = torch.acos(cosine_similarity)
angular_distance_degrees = angular_distance_radians * (180 / torch.pi)

print("Angular distance between users (radians):", angular_distance_radians.item())
print("Angular distance between users (degrees):", angular_distance_degrees.item())


Angular distance between users (radians): 0.7854077816009521
Angular distance between users (degrees): 45.000553131103516


* `Tensor.add()` adds a scaler/tenosr to current tensor. opetioanll scaling the value by a factor/alpha
* `Tensor.addbmm()` perform batch matrix-matrix multiplication and adds the result to a base tensor optionall scalling the input with beta and alpha
* `Tensor.addcdiv()` perform an element-wise division of two tensors and adds the result scaled by a factor value to the base tensor.
* `Tensor.addcmul()` perform element-wise multiplication of two tensors by a faactor vaue and adds it ot the base tensor
* `Tensor.addmm()` perform matrix multiplication between two matrices and adds the result , scaled by a dactor alpha to the base tensor scaled by another factor beta
* `Tensor.addmv()` performs a matrix-vector multiplication between a matrix and a vector scales the result by a factor, and adds it to a base tensor scaled by another factor beta , this is equivalent to calling torch.addmv()
* `Tensor.addjoint()` computes conjugate transpose of a tensor it is particularlt useful for complex-values tensors



In [8]:
import torch 

tensor = torch.tensor([[1,2],[3,4]])

result_scalar = tensor.add(5)
print(result_scalar)

other_tensor = torch.tensor([[10,20],[30,40]])
result_tensor = tensor.add(other_tensor)
print(result_tensor)

scaled_result = tensor.add(other_tensor, alpha=2)
print(scaled_result)

broadcast_tensor = torch.tensor([1,2]) # add a 1D tensor to a 2d tensor
broadcast_result = tensor.add(broadcast_tensor)
print(broadcast_result)

tensor([[6, 7],
        [8, 9]])
tensor([[11, 22],
        [33, 44]])
tensor([[21, 42],
        [63, 84]])
tensor([[2, 4],
        [4, 6]])


In [13]:
import torch

# Create a base tensor (to which the result will be added)
base_tensor = torch.tensor([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])  # New shape: [2, 3]
print("Base Tensor:")
print(base_tensor)

# Create batch1 and batch2 tensors for batch matrix multiplication
batch1 = torch.randn(3, 2, 4)  # Shape: (batch_size=3, n=2, k=4)
batch2 = torch.randn(3, 4, 3)  # Shape: (batch_size=3, k=4, m=3)

# Perform addbmm with default beta=1 and alpha=1
result = base_tensor.addbmm(batch1, batch2)
print("\nResult after addbmm (default beta=1, alpha=1):")
print(result)

# Perform addbmm with custom beta=0.5 and alpha=2.0
result_custom = base_tensor.addbmm(batch1, batch2, beta=0.5, alpha=2.0)
print("\nResult after addbmm (beta=0.5, alpha=2.0):")
print(result_custom)

Base Tensor:
tensor([[1., 2., 3.],
        [4., 5., 6.]])

Result after addbmm (default beta=1, alpha=1):
tensor([[ 6.7329,  6.4835,  3.8324],
        [ 5.5145, 14.5752,  9.9945]])

Result after addbmm (beta=0.5, alpha=2.0):
tensor([[11.9657,  9.9670,  3.1648],
        [ 5.0290, 21.6504, 10.9890]])


In [14]:
import torch

# Create a base tensor
base_tensor = torch.tensor([[1.0, 2.0], [3.0, 4.0]])
print("Base Tensor:")
print(base_tensor)

# Create tensor1 and tensor2 for element-wise division
tensor1 = torch.tensor([[10.0, 20.0], [30.0, 40.0]])
tensor2 = torch.tensor([[2.0, 4.0], [6.0, 8.0]])

# Perform addcdiv with default value=1
result_default = base_tensor.addcdiv(tensor1, tensor2)
print("\nResult after addcdiv (default value=1):")
print(result_default)

# Perform addcdiv with custom value=0.5
result_custom = base_tensor.addcdiv(tensor1, tensor2, value=0.5)
print("\nResult after addcdiv (value=0.5):")
print(result_custom)

# Broadcasting example: Addcdiv with smaller tensors
base_tensor_broadcast = torch.tensor([[1.0, 2.0], [3.0, 4.0]])
tensor1_broadcast = torch.tensor([10.0, 20.0])  # Shape: [2]
tensor2_broadcast = torch.tensor([2.0, 4.0])   # Shape: [2]

result_broadcast = base_tensor_broadcast.addcdiv(tensor1_broadcast, tensor2_broadcast)
print("\nResult after broadcasting addcdiv:")
print(result_broadcast)

Base Tensor:
tensor([[1., 2.],
        [3., 4.]])

Result after addcdiv (default value=1):
tensor([[6., 7.],
        [8., 9.]])

Result after addcdiv (value=0.5):
tensor([[3.5000, 4.5000],
        [5.5000, 6.5000]])

Result after broadcasting addcdiv:
tensor([[6., 7.],
        [8., 9.]])


In [3]:
#addcmul

import torch 

base_tensor = torch.tensor([[1.0,2.0],[3.0,4.0]])
print('base tensor:')
print(base_tensor)

# create tensor1 and tensor2 for element-wise multiplication
tensor1 = torch.tensor([[10.0,20.0], [30.0,40.0]])
tensor2 = torch.tensor([[2.0,3.0],[4.0,5.0]])

#perform addcmul with default value=1
result_default = base_tensor.addcmul(tensor1, tensor2)
print('\nresult after cmul (default value=1)')
print(result_default)

result_custom = base_tensor.addcmul(tensor1, tensor2, value=0)
print('\n Result after addcmul (value=0.5)')
print(result_custom)

#broadcasting example : addcmul with smaller tensors
base_tensor_broadcast = torch.tensor([[1.0,2.0],[3.0,4.0]])
tensor1_broadcast = torch.tensor([10.0, 20.0])
tensor2_broadcast = torch.tensor([2.0,3.0])

result_broadcast = base_tensor_broadcast.addcmul(tensor1_broadcast, tensor2_broadcast)
print('\n result after broadcasting addcmul:')
print(result_broadcast)


base tensor:
tensor([[1., 2.],
        [3., 4.]])

result after cmul (default value=1)
tensor([[ 21.,  62.],
        [123., 204.]])

 Result after addcmul (value=0.5)
tensor([[1., 2.],
        [3., 4.]])

 result after broadcasting addcmul:
tensor([[21., 62.],
        [23., 64.]])


In [4]:
#addmm

print(base_tensor)

mat1 = torch.randn(2,3)
mat2 = torch.randn(3,2)

result_default = base_tensor.addmm(mat1, mat2)
print('result after addmm (default beta=1, alpha=1)')
print(result_default)

#perform addmm with custom beta=0.5 and alpha=2.0
result_custom = base_tensor.addmm(mat1, mat2, beta=0.5, alpha=2.0)
print('\nresult after addmm (beta=0.5, alpha=2.0):')
print(result_custom)

#broadcasting base tensor with shape [1,2]
base_tensor_broadcast = torch.tensor([[1.0,2.0]])
result_broadcast = base_tensor_broadcast.addmm(mat1 , mat2)
print('\n result after broadcasting addmm:')
print(result_broadcast)

tensor([[1., 2.],
        [3., 4.]])
result after addmm (default beta=1, alpha=1)
tensor([[ 0.5669, -2.3521],
        [ 3.3084,  8.5904]])

result after addmm (beta=0.5, alpha=2.0):
tensor([[-0.3661, -7.7041],
        [ 2.1169, 11.1808]])

 result after broadcasting addmm:
tensor([[ 0.5669, -2.3521],
        [ 1.3084,  6.5904]])


In [10]:
import torch

# Create a sparse base tensor (self)
indices = torch.tensor([[0, 1], [1, 2]])  # Indices of non-zero elements
values = torch.tensor([3.0, 4.0])         # Values of non-zero elements
size = (3, 3)                             # Size of the sparse tensor
sparse_tensor = torch.sparse_coo_tensor(indices, values, size)
print("Sparse Base Tensor:")
print(sparse_tensor)

# Create dense mat1 and mat2 for matrix multiplication
mat1 = torch.tensor([[ 0.7740, -0.6338],
                     [ 0.1909, -0.4897],
                     [-0.4463, -0.3699]])

mat2 = torch.tensor([[ 0.6267, -0.1466,  0.4464],
                     [-0.4601, -0.1870, -0.9420]])
# Perform sspaddmm with default beta=1 and alpha=1
result_default = sparse_tensor.sspaddmm(mat1, mat2)
print("\nResult after sspaddmm (default beta=1, alpha=1):")
print(result_default)

# Perform sspaddmm with custom beta=0.5 and alpha=2.0
result_custom = sparse_tensor.sspaddmm(mat1, mat2, beta=0.5, alpha=2.0)
print("\nResult after sspaddmm (beta=0.5, alpha=2.0):")
print(result_custom)

Sparse Base Tensor:
tensor(indices=tensor([[0, 1],
                       [1, 2]]),
       values=tensor([3., 4.]),
       size=(3, 3), nnz=2, layout=torch.sparse_coo)


RuntimeError: sspaddmm: Argument #2: matrices expected, got 0D tensor

In [1]:
import torch 

base_tensor = torch.tensor([1.0,2.0])
print('base tensor')
print(base_tensor)

mat = torch.tensor([[1.0,2.0,3.0],[4.0,5.0,6.0]])
vec = torch.tensor([1.0,2.0,3.0])

# perform addmv with default beta=1 and alpha=1
result_default = base_tensor.addmv(mat, vec)
print('\rresult after addmv (default beta=1, alpha=1):')
print(result_default)

#perform addmv with custom beta=0.5 and alpha=2.0
result_custom = base_tensor.addmv(mat, vec, beta=0.5, alpha=2.0)
print('\nresult after addmv (beta=0.5, alpha=2.0)')
print(result_custom)

base tensor
tensor([1., 2.])
result after addmv (default beta=1, alpha=1):
tensor([15., 34.])

result after addmv (beta=0.5, alpha=2.0)
tensor([28.5000, 65.0000])


In [2]:
import torch 

base_matrix = torch.tensor([[1.0,2.0],[3.0,4.0]])
print('base matrix')
print(base_matrix)

vec1 = torch.tensor([1.0,2.0])
vec2 = torch.tensor([3.0,4.0])

result_default = base_matrix.addr(vec1, vec2)
print('\n result after addr (default beta=1 alpha=1):')
print(result_default)

result_custom = base_matrix.addr(vec1, vec2, beta=0.5, alpha=2.0)
print('\nresult after addr (beta=0.5, alpha=2.0)')
print(result_custom)

#perform addr_
base_matrix.addr_(vec1,vec2, beta=0.5, alpha=2.0)
print('\n base matrix after add_ (in-place modification)')
print(base_matrix)

base matrix
tensor([[1., 2.],
        [3., 4.]])

 result after addr (default beta=1 alpha=1):
tensor([[ 4.,  6.],
        [ 9., 12.]])

result after addr (beta=0.5, alpha=2.0)
tensor([[ 6.5000,  9.0000],
        [13.5000, 18.0000]])

 base matrix after add_ (in-place modification)
tensor([[ 6.5000,  9.0000],
        [13.5000, 18.0000]])


In [3]:
#addjoint()

tensor1 = torch.tensor([1.0,2.0,3.0])
tensor2 = torch.tensor([1.0,2.00001,3.0])

are_close_default = torch.allclose(tensor1, tensor2)
print('are tensors close with default tolerences', are_close_default)

are_close_custom = torch.allclose(tensor1, tensor2, rtol=1e-5, atol=1e-8)
print('are tensors close with custom tolerances?', are_close_custom)

tensor3 = torch.tensor([1.0,2.1,3.0])
are_not_close = torch.allclose(tensor1, tensor3)
print('are tensors not close?', are_not_close)


are tensors close with default tolerences True
are tensors close with custom tolerances? True
are tensors not close? False


In [ ]:
# checks if all elements of two tensors are close withihon tolerance

#allclose

a = torch.tensor([1.0,2.0,3.0])
b = torch.tensor([1.0,2.00001,2.99999])

print(torch.allclose(a,b)) # True 

c = torch.tensor([1.0,2.1,3.0])
print(torch.allclose(a,c))  # False

# maximum value of all elements or along a specific dimentsion
# amax()
x = torch.tensor([[1,2,3],[4,5,6]])
print(torch.amax(x))

# returns the minimum value similarly
#amin()
print(torch.amin(x))
print(torch.amin(x,dim=1))

# returns both min and max at the same time
#aminmax
min_vals , max_vals = torch.aminmax(, dim=1)
print("Min:", min_vals)
print("Max:", max_vals)


# computes the angle in randians of each element in a complex-valued tensor
# angle()
tensor = torch.tensor([1 + 1j, -1 -1j], dtype=torch.cfloat)
print('complex tensor:')
print(tensor)

angles = tensor.angle()
print('\nangles in radians')
print(angles)

#  applies a function to each element of the tensor in-place
tensor = torch.tensor([1.0,2.0,3.0,4.0])
print('original tensor:')
print(tensor)

tensor.apply_(lambda x:x ** 2)
print('\n tensor after applyingi lambda functions:')
print(tensor)

#returns the index of the maximum value along a specified dimension

tensor = torch.tensor([[1,3,4],[2,4,6]])
print('tensor:')
print(tensor)

argmax_result = tensor.argmax(dim=1)
print('\nindex of maximum value along dim=1')
print(argmax_result)

#returns the index of the minimum value along a specified dimension
print('\nindex of the minimum value along dim=1',tensor.argmin(dim=1))

#returns the indices that would sort the tensor along a specified dimension
#argsort()
tensor = torch.tensor([3,1,4,2])
print('\nindices that would sort the tensor:', tensor.argsort())

# returns the indices of non-zero elements in the tensor
#argwhere()
tensor = torch.tensor([[0,1],[2,0]])
print('\nindices of non-zero elements:', tensor.argwhere())

#computes the arcsine(inverse sine) of each element in the tensor
#asin #arcsine
tensor = torch.tensor([-1.0,0.0,1.0])
print('\narcsine of each element',tensor.asin())

# creates a view of the tensor with specified sizez, stride and storage offset . useful for advanced tensor amnipulations but should be used carefully as it can lead to undefined behaviur if misused
# as_stride()
tensor = torch.arange(9).reshapep(3,3)
print('\nstirded tensor (size=(2,2), stride=(3,1)):',torch.as_strided(tensor, size=(2,2), stride=(3,1)))

#computes the artangent of eaech element in the tensor
#atan
tensor = torch.tensor([0.0, 1.0, -1.0])
print("\nArctangent of each element:",tensor.atan())

# computes the element-wise arctangent of two tensors , considering their signs ot determine the correct quadrant
tensor1 = torch.tensor([1.0, -1.0, 1.0])
tensor2 = torch.tensor([1.0, 1.0, -1.0])

print("\nElement-wise atan2 result:",torch.atan2(tensor1, tensor2))

#check if all elements in the tensor evaluate to True along a specified dimension
#all
tensor = torch.tensor([[True, True], [True, False]])
print("\nAre all elements True?", tensor.all())
print("\nAre all elements True along dim=0?",tensor.all(dim=0))

#checks if any element i the tensor evalutes to True along a specified dimension
#any()

tensor = torch.tensor([[False, False], [True, False]])
print("\nIs any element True?",tensor.any())
print("\nIs any element True along dim=1?",tensor.any(dim=1))


# computes the gradient of the current tensor with respect to graph leaves . this is used in autograd for back propagation
# backward()
x = torch.tensor([2.0, 3.0], requires_grad=True)
y = x.pow(2).sum()
y.backward() #compute gradients
print("Gradients of x:")
print(x.grad)

#performs batch matrix-matrix addition and multiplication 
#baddbmm
batch1 = torch.randn(2, 3, 4)  # Shape: [2, 3, 4]
batch2 = torch.randn(2, 4, 5)  # Shape: [2, 4, 5]
base_tensor = torch.randn(2, 3, 5)  # Shape: [2, 3, 5]
print("Result of baddbmm:",base_tensor.baddbmm(batch1, batch2, beta=0.5, alpha=2.0))

#returns a tensor where each element is independently sampled from a bernoulli distribution defined by the input tensor's values
#bernoulli()
probs = torch.tensor([0.3, 0.7, 0.5])
print("\nBernoulli Samples:", probs.bernoulli())


