In [ ]:
#https://pytorch.org/docs/stable/nn.functional.html

In [ ]:
#transpose1d 

#applies a 1D transposed convolution to an input signal

import torch 
import torch.nn.functional as F 

inputs = torch.randn(2,16,50) 
weights = torch.randn(16,33,5)

bias = torch.rand(33)

output = F.conv_transpose1d(
    input = inputs,
    weight = weights,
    bias = bias,
    stride = 2,
    padding = 1,
    output_padding=1,
    groups=1,
    dilation=1
)

print('Input shape:',inputs.shape)
print('Weight shape:', weights.shape)
print('Bias shape:', bias.shape)
print('Output shape:', output.shape)

Input shape: torch.Size([2, 16, 50])
Weight shape: torch.Size([16, 33, 5])
Bias shape: torch.Size([33])
Output shape: torch.Size([2, 33, 102])


In [2]:
#transpose2d

#applies 2d transposed convolution to an input image. 
# Transposed convolutions are commonly used in tasks like upsampling image generation and semantic segmentations

import torch 
import torch.nn as nn

# batch_size = 1, in_channels = 4 , h = 5 w =5
inputs = torch.randn(1,4,5,5)

# in_channel = 4 , out_channels = 8 kernel_height = 3, kernel_width = 3
weights = torch.randn( 4, 8, 3,3)
bias = torch.randn(8)

output = F.conv_transpose2d(
    input = inputs,
    weight = weights,
    bias = bias,
    stride = 2,
    padding = 1,
    output_padding = 1,
    groups = 1,
    dilation =1
)

print('Input shape:',inputs.shape)
print('Weight shape:',weights.shape)
print('Bias shape:',bias.shape)
print('Output shape:', output.shape)


Input shape: torch.Size([1, 4, 5, 5])
Weight shape: torch.Size([4, 8, 3, 3])
Bias shape: torch.Size([8])
Output shape: torch.Size([1, 8, 10, 10])


In [3]:
#transpose3d 

#function applies a 3d transposed convolution to a 3d tensor
#transposed convolutions in 3d are commonly used in tasks like volumetric upsamping ,medical imagin and video processing

import torch 
import torch.nn.functional as F

# define input tensor
    # batch_size = 2 , in_channels = 16, depth = 50, kernel_height =3, kernel_widht = 3
inputs = torch.randn(2,16,50,10,20) 

#define weight tensor
    #in_channels = 16, out_channels =33, kernel_depth=3, kernel_height=3, kernel_width =3
weights = torch.randn(16,33,3,3,3)

bias = torch.randn(33) #define optional bias tensor (Out_channel = 33)

output = F.conv_transpose3d(
    input=inputs,
    weight=weights,
    bias = bias,
    stride =2, #stride of the conv
    padding = 1,
    output_padding =1,
    groups = 1,
    dilation =1 #dilation rate
)

print('Input shaoe:',inputs.shape)
print('Weight shape:',weights.shape)
print('Bias shape:', bias.shape)
print('Output shape:', output.shape)

Input shaoe: torch.Size([2, 16, 50, 10, 20])
Weight shape: torch.Size([16, 33, 3, 3, 3])
Bias shape: torch.Size([33])
Output shape: torch.Size([2, 33, 100, 20, 40])


In [ ]:
#http://turbolearn.ai/

In [ ]:
#unfold 

# function extracts sliding local bloacls from batched input tensor
# this is commonly used in tasks like convolutional neural networks where you need to extract small regions of an image for processing

import torch 
import torch.nn.functional as F 

#define a 4d input
    # batch_size = 1 , channels =3, height = 4, width =4
input_tensor = torch.arange(48, dtype=torch.float32).reshape(1,3,4,4)
print('Input Tensor Shape:', input_tensor.shape)
print('Input Tensor:\n', input_tensor)

#parameters for the unfold operation
kernel_size = (2,2)
stride = 1
padding = 0
dilation = 1

unfolded = F.unfold(input=input_tensor, kernel_size = kernel_size, stride=stride, padding=padding, dilation=dilation)

#print the unfolder tensor
print('\n Unfolder Tensor Shape:',unfolded.shape)
print('Unfolded Tensor:\n', unfolded)

#fold
#Optinaly , fold the tensor back to its original shape
#it aggragtes overlapping patches using summation by default
folded = F.fold(input=unfolded, output_size=(4,4),kernel_size=kernel_size, padding=padding, dilation=dilation)
print('\nFolded Tensor Shape:', folded.shape)
print('Folded Tensor:\n', folded)

Input Tensor Shape: torch.Size([1, 3, 4, 4])
Input Tensor:
 tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]],

         [[16., 17., 18., 19.],
          [20., 21., 22., 23.],
          [24., 25., 26., 27.],
          [28., 29., 30., 31.]],

         [[32., 33., 34., 35.],
          [36., 37., 38., 39.],
          [40., 41., 42., 43.],
          [44., 45., 46., 47.]]]])

 Unfolder Tensor Shape: torch.Size([1, 12, 9])
Unfolded Tensor:
 tensor([[[ 0.,  1.,  2.,  4.,  5.,  6.,  8.,  9., 10.],
         [ 1.,  2.,  3.,  5.,  6.,  7.,  9., 10., 11.],
         [ 4.,  5.,  6.,  8.,  9., 10., 12., 13., 14.],
         [ 5.,  6.,  7.,  9., 10., 11., 13., 14., 15.],
         [16., 17., 18., 20., 21., 22., 24., 25., 26.],
         [17., 18., 19., 21., 22., 23., 25., 26., 27.],
         [20., 21., 22., 24., 25., 26., 28., 29., 30.],
         [21., 22., 23., 25., 26., 27., 29., 30., 31.],
         [32., 33., 34., 36., 37., 

In [6]:
#avg_pool1d

# applies 1d average pooling over an input singal
# used in tasks like time series analysis or audio processing 

import torch
import torch.nn.functional as F 

#define a 3d input tensor 
    #batch_size = 1, channels = 1, length =7
input_tensor = torch.tensor([[1,2,3,4,5,6,7]], dtype = torch.float32)

print('Input Tensor Shape:', input_tensor.shape)
print('Input Tensor:\n',input_tensor)

kernel_size = 3,
stride = 2
padding = 0
ceil_mode = False
count_include_pad = True 

#aaply 1d average pooling 
output = F.avg_pool1d(
    input = input_tensor,
    kernel_size = kernel_size,
    stride = stride ,
    padding = padding,
    ceil_mode = ceil_mode,
    count_include_pad = count_include_pad
)

print('\nOutput Tensor Shape:', output.shape)
print('Output Tensor:\n', output)

Input Tensor Shape: torch.Size([1, 7])
Input Tensor:
 tensor([[1., 2., 3., 4., 5., 6., 7.]])

Output Tensor Shape: torch.Size([1, 3])
Output Tensor:
 tensor([[2., 4., 6.]])


In [11]:
#torch.nn.functional.avg_pool2d 

# function applies 2d average pooling over an input image or feature map
# commonly used in CNN for downsampling

import torch 
import torch.nn.functional as F

#define 4d input tensor
    #batch_size =1, channels=1, height=6, width=6
input_tensor = torch.arange(36, dtype=torch.float32).reshape(1, 1, 6, 6)
print("Input Tensor Shape:", input_tensor.shape)
print("Input Tensor:\n", input_tensor)

# Parameters for the avg_pool2d operation
kernel_size = (2, 2)  # Size of the pooling window
stride = (2, 2)       # Stride of the pooling window
padding = 0           # Padding added to the input
ceil_mode = False     # Use floor instead of ceil to compute output size
count_include_pad = True  # Include zero-padding in averaging calculation
divisor_override = None   # Use the default divisor (pooling region size)

# Apply 2D average pooling
output = F.avg_pool2d(
    input=input_tensor,
    kernel_size=kernel_size,
    stride=stride,
    padding=padding,
    ceil_mode=ceil_mode,
    count_include_pad=count_include_pad,
    divisor_override=divisor_override
)

# Print the output tensor
print("\nOutput Tensor Shape:", output.shape)
print("Output Tensor:\n", output)



Input Tensor Shape: torch.Size([1, 1, 6, 6])
Input Tensor:
 tensor([[[[ 0.,  1.,  2.,  3.,  4.,  5.],
          [ 6.,  7.,  8.,  9., 10., 11.],
          [12., 13., 14., 15., 16., 17.],
          [18., 19., 20., 21., 22., 23.],
          [24., 25., 26., 27., 28., 29.],
          [30., 31., 32., 33., 34., 35.]]]])

Output Tensor Shape: torch.Size([1, 1, 3, 3])
Output Tensor:
 tensor([[[[ 3.5000,  5.5000,  7.5000],
          [15.5000, 17.5000, 19.5000],
          [27.5000, 29.5000, 31.5000]]]])
