In [1]:
import torch 

float32_tensor = torch.tensor([1.0,2.0,3.0], dtype=torch.float32)
float64_tensor = torch.tensor([1.0,2.0,3.0], dtype=torch.float64)
float16_tensor = torch.tensor([1.0,2.0,3.0],dtype=torch.float16)
bfloat16_tensor = torch.tensor([1.0,2.0,3.0], dtype=torch.bfloat16)
complex32_tensor = torch.tensor([1 + 2j, 3 + 4j], dtype=torch.complex32)
complex64_tensor = torch.tensor([1 + 2j, 3 + 4j], dtype= torch.complex64)
complex128_tensor = torch.tensor([1 + 2j, 3 + 4j], dtype= torch.complex128)
uint8_tensor = torch.tensor([1,2,3],dtype=torch.uint8)
uint16_tensor = torch.tensor([1,2,3], dtype=torch.uint16)
uint32_tensor = torch.tensor([1,2,3], dtype=torch.uint32)
uint64_tensor = torch.tensor([1,2,3], dtype=torch.uint64)
int8_tensor = torch.tensor([1,2,3],dtype=torch.int8)
int16_tensor = torch.tensor([1,2,3], dtype=torch.int16)
int32_tensor = torch.tensor([1,2,3], dtype=torch.int32)
int64_tensor = torch.tensor([1,2,3], dtype=torch.int64)
bool_tensor = torch.tensor([True, False , True], dtype=torch.bool)
quint8_tensor = torch.quantize_per_tensor(torch.tensor([1.0,2.0,3.0]), scale=1.0, zero_point=0, dtype=torch.quint8)
qint8_tensor = torch.quantize_per_tensor(torch.tensor([1.0,2.0,3.0]), scale=1.0, zero_point=0, dtype=torch.qint8)
qint32_tensor = torch.quantize_per_tensor(torch.tensor([1.0,2.0,3.0]), scale=1.0, zero_point=0, dtype=torch.qint32)
quint4x2_tensor = torch.quantize_per_tensor(torch.tensor([1.0,2.0,3.0]), scale=1.0, zero_point=0, dtype= torch.quint4x2)

# if hasattr(torch, 'float8_e4m3fn'):
    # float8_e43fn_tensor = torch.tensor([1.0,2.0,3.0], dtype=torch.float8_e43fn)
if hasattr(torch, 'float8_e5m2'):
    float8_e5m2_tensor = torch.tensor([1.0,2.0,3.0], dtype=torch.float8_e5m2)


print("32-bit floating point (torch.float32):", float32_tensor)
print("64-bit floating point (torch.float64):", float64_tensor)
print("16-bit floating point (torch.float16):", float16_tensor)
print("16-bit brain floating point (torch.bfloat16):", bfloat16_tensor)
print("32-bit complex (torch.complex32):", complex32_tensor)
print("64-bit complex (torch.complex64):", complex64_tensor)
print("128-bit complex (torch.complex128):", complex128_tensor)
print("8-bit integer (unsigned) (torch.uint8):", uint8_tensor)
print("16-bit integer (signed) (torch.int16):", uint16_tensor)
print("32-bit integer (signed) (torch.int32):", uint32_tensor)
print("64-bit integer (signed) (torch.int64):", uint64_tensor)
print("8-bit integer (signed) (torch.int8):", int8_tensor)
print("16-bit integer (signed) (torch.int16):", int16_tensor)
print("32-bit integer (signed) (torch.int32):", int32_tensor)
print("64-bit integer (signed) (torch.int64):", int64_tensor)
print("Boolean (torch.bool):", bool_tensor)
print("Quantized 8-bit integer (unsigned) (torch.quint8):", quint8_tensor)
print("Quantized 8-bit integer (signed) (torch.qint8):", qint8_tensor)
print("Quantized 32-bit integer (signed) (torch.qint32):", qint32_tensor)
print("Quantized 4-bit integer (unsigned) (torch.quint4x2):", quint4x2_tensor)
print("8-bit floating point, e5m2 (torch.float8_e5m2):", float8_e5m2_tensor)


32-bit floating point (torch.float32): tensor([1., 2., 3.])
64-bit floating point (torch.float64): tensor([1., 2., 3.], dtype=torch.float64)
16-bit floating point (torch.float16): tensor([1., 2., 3.], dtype=torch.float16)
16-bit brain floating point (torch.bfloat16): tensor([1., 2., 3.], dtype=torch.bfloat16)
32-bit complex (torch.complex32): tensor([1.+2.j, 3.+4.j], dtype=torch.complex32)
64-bit complex (torch.complex64): tensor([1.+2.j, 3.+4.j])
128-bit complex (torch.complex128): tensor([1.+2.j, 3.+4.j], dtype=torch.complex128)
8-bit integer (unsigned) (torch.uint8): tensor([1, 2, 3], dtype=torch.uint8)
16-bit integer (signed) (torch.int16): tensor([1, 2, 3], dtype=torch.uint16)
32-bit integer (signed) (torch.int32): tensor([1, 2, 3], dtype=torch.uint32)
64-bit integer (signed) (torch.int64): tensor([1, 2, 3], dtype=torch.uint64)
8-bit integer (signed) (torch.int8): tensor([1, 2, 3], dtype=torch.int8)
16-bit integer (signed) (torch.int16): tensor([1, 2, 3], dtype=torch.int16)
32-bit

C:\Users\fadzw\AppData\Local\Temp\ipykernel_18756\2747244299.py:7: UserWarning: ComplexHalf support is experimental and many operators don't support it yet. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\EmptyTensor.cpp:51.)
  complex32_tensor = torch.tensor([1 + 2j, 3 + 4j], dtype=torch.complex32)


In [1]:
#Tensor.new_tensor

import torch 

base_tensor = torch.ones((2,), dtype=torch.int8)
print('base tensor:',base_tensor)

data = [[0,1],[2,3]]
#same dtype and device as the base tensor
new_tensor_default = base_tensor.new_tensor(data)
print('\nnew tensor (default):', new_tensor_default)

#specify a different dtype
new_tensor_float32 = base_tensor.new_tensor(data,dtype=torch.float32)
print('\nnew tensor (dtype=torch.float32):',new_tensor_float32)

#specify a different device
if torch.cuda.is_available():
    new_tensr_cuda = base_tensor.new_tensor(data, device='cuda')
    print('\n new tensor (device=cuda):',new_tensor_cuda)
else:
    print('\ncuda is not available. skipping GPU example')


#specify requier_grad=True for autograd tracking
new_tensor_requires_grad = base_tensor.new_tensor(data,dtype=torch.float32, requires_grad=True)
print('\n new tensor (requires_grad)=True:',new_tensor_requires_grad)

#perform a dummy operation to demonstrate autograd
output = new_tensor_requires_grad.sum()
output.backward()
print('Gradient of New Tensor:',new_tensor_requires_grad.grad)

#specify layout (default is torch.strided)
# new_tensor_strided = base_tensor.new_tensor(data, layout=torch.strided)
# print('\n new tensor (layout=torch.strided):',new_tensor_strided)

#specify pin_memory=True (only works for CPU tensors)
# new_tensor_pinned = base_tensor.new_tensor(data, pin_memory=True)
# print('\n new tensor (pin_memory=True):',new_tensor_pinned)

# Alternative for pin_memory=True (only works for CPU tensors)
# pinned_tensor = torch.tensor(data, dtype=torch.int8).pin_memory() #RuntimeError: Cannot access accelerator device when none is available.
# print("\nPinned Tensor (pin_memory=True):", pinned_tensor)


# Alternative for sparse layout
indices = torch.tensor([[0, 1], [1, 0]])
values = torch.tensor([3, 4], dtype=torch.float32)
sparse_tensor = torch.sparse_coo_tensor(indices, values, size=(2, 2))
print("\nSparse Tensor (layout=torch.sparse_coo):", sparse_tensor)

base tensor: tensor([1, 1], dtype=torch.int8)

new tensor (default): tensor([[0, 1],
        [2, 3]], dtype=torch.int8)

new tensor (dtype=torch.float32): tensor([[0., 1.],
        [2., 3.]])

cuda is not available. skipping GPU example

 new tensor (requires_grad)=True: tensor([[0., 1.],
        [2., 3.]], requires_grad=True)
Gradient of New Tensor: tensor([[1., 1.],
        [1., 1.]])

Sparse Tensor (layout=torch.sparse_coo): tensor(indices=tensor([[0, 1],
                       [1, 0]]),
       values=tensor([3., 4.]),
       size=(2, 2), nnz=2, layout=torch.sparse_coo)


In [2]:
#Tensor.new_full

# creates a tensor for a spcified size filled with a given value and inherits properties like dtype and devvice from the original tensor unless overridden

import torch 

tensor = torch.ones((2,), dtype=torch.float64)

print('original tensor:')
print(tensor)
print('dtype:',tensor.dtype)
print('device',tensor.device)

#create a new tensor for size 3 4 filled with 3.141592
new_tensor = tensor.new_full((3,4),3.141592)

print('\n new tensor (inherits dtype and device from original)')
print(new_tensor)
print('dtype:',new_tensor.dtype)
print('device:',new_tensor.device)

#create a new tensor on a different device and dtype
if torch.cuda.is_available():
    new_tensor_gpu = tensor.new_full(
        size=(2,3),
        fill_value=2.718,
        dtype=torch.float32,
        device='cuda'
    )
    print('\nenw tensor on GPU with dtype = torch.float32')
    print(new_tensor_gpu)
    print('dtype:',new_tensor_gpu.dtype)
    print('device:',new_tensor_gpu.device)
else:
    print('\nCUDA is not available. Skipping GPU tensor creation.')

original tensor:
tensor([1., 1.], dtype=torch.float64)
dtype: torch.float64
device cpu

 new tensor (inherits dtype and device from original)
tensor([[3.1416, 3.1416, 3.1416, 3.1416],
        [3.1416, 3.1416, 3.1416, 3.1416],
        [3.1416, 3.1416, 3.1416, 3.1416]], dtype=torch.float64)
dtype: torch.float64
device: cpu

CUDA is not available. Skipping GPU tensor creation.


In [3]:
#Tensor.new_empty

# creates a new tensor of a specified size, filled with uninitialized data. 
# the new tensor inherits properties like dtype and device from the original tensor unless overridden

import torch 

tensor = torch.ones((2,),dtype=torch.float64)

print('original tensor:')
print(tensor)
print('dtype:',tensor.dtype)
print('device:', tensor.device)

new_tensor = tensor.new_empty((3,4))

print('\n new empty tensor (inherits dtype and device from original):')
print(new_tensor)
print('dtype:', new_tensor.dtype)
print('device:', new_tensor.device)

#create a new empty tensor on a different device
if torch.cuda.is_available():
    new_tensor_gpu = tensor.new_empty(
        size=(2,3),
        dtype=torch.float32,
        device ='cuda'
    )
    print('\n new empty tensor on GPU with dtype=torch.float32')
    print(new_tensor_gpu)
    print('dtype:', new_tensor_gpu.dtype)
    print('dtype:', new_tensor_gpu.device)
else:
    print('\nCUDA is not available . Skipping GPU tensor creation')

original tensor:
tensor([1., 1.], dtype=torch.float64)
dtype: torch.float64
device: cpu

 new empty tensor (inherits dtype and device from original):
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]], dtype=torch.float64)
dtype: torch.float64
device: cpu

CUDA is not available . Skipping GPU tensor creation


In [4]:
#Tensor.new_ones

# creates a new tensor of a specified size, fillwd with ones.  THe new tensor inherits properties like dtype an device from the orignal tensor uness overridden

import torch 
tensor = torch.tensor((),dtype=torch.int32)

print('original tensor:')
print(tensor)
print('dtype:',tensor.dtype)
print('device:',tensor.device)

#filled with ones
new_tensor = tensor.new_ones((2,3))
print('\n nre tensosr filled with ones (inherits dtype and device from original:)')
print(new_tensor)
print('dtype:',new_tensor.dtype)

print('device:',new_tensor.device)

# create a tensor on a different device and a dtype
if torch.cuda.is_available():
    new_tensor_gpu = tensor.new_ones(
        size=(3,2),
        dtype=torch.float32,
        devicee='cuda'
    )
    print('\nNew tensor filled with ones on GPU with dtype=torch.float32')
    print(new_tensor_gpu)
    print('dtype:',new_tensor_gpu.dtype)
    print('device:',new_tensor_gpu.device)
else:
    print('\n CUDA is not available . Skipping GPU tensor creation')

original tensor:
tensor([], dtype=torch.int32)
dtype: torch.int32
device: cpu

 nre tensosr filled with ones (inherits dtype and device from original:)
tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)
dtype: torch.int32
device: cpu

 CUDA is not available . Skipping GPU tensor creation


In [6]:
#Tensor.new_zeros

# creates a new tensor of a specified size, fillwd with ones.  THe new tensor inherits properties like dtype an device from the orignal tensor uness overridden

import torch 
tensor = torch.tensor((),dtype=torch.int32)

print('original tensor:')
print(tensor)
print('dtype:',tensor.dtype)
print('device:',tensor.device)

#filled with ones
new_tensor = tensor.new_zeros((2,3))
print('\n nre tensosr filled with ones (inherits dtype and device from original:)')
print(new_tensor)
print('dtype:',new_tensor.dtype)

print('device:',new_tensor.device)

# create a tensor on a different device and a dtype
if torch.cuda.is_available():
    new_tensor_gpu = tensor.new_zeros(
        size=(3,2),
        dtype=torch.float32,
        devicee='cuda'
    )
    print('\nNew tensor filled with ones on GPU with dtype=torch.float32')
    print(new_tensor_gpu)
    print('dtype:',new_tensor_gpu.dtype)
    print('device:',new_tensor_gpu.device)
else:
    print('\n CUDA is not available . Skipping GPU tensor creation')

#Tensor.is_cuda
# is True if the Tensor is sotred on the GPU False otherwise

original tensor:
tensor([], dtype=torch.int32)
dtype: torch.int32
device: cpu

 nre tensosr filled with ones (inherits dtype and device from original:)
tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)
dtype: torch.int32
device: cpu

 CUDA is not available . Skipping GPU tensor creation


In [8]:
#Tnesor.is_quqntized

#property checks whether a tensor is quantized or not.
# quantized tensors are sued in pytoch for low-precision computations , typically in scenarios like model optimmization for deployment on resrouce-contrained devices.

import torch 
float_tensor = torch.tensor([1.0,2.0,3.0], dtype=torch.float32)

print('is float_tensor quantized?')
print(float_tensor.is_quantized)

quantized_tensor = torch.quantize_per_tensor(
    float_tensor, scale=0.1, zero_point=0, dtype=torch.quint8
)

#check if tensor is quantized
print('\nis quantized_tensor quantized?')
print(quantized_tensor.is_quantized)

# print details of the quantized tensor
print('\n tensor details')
print(quantized_tensor)
print('scale', quantized_tensor.q_scale())
print('zero point:', quantized_tensor.q_zero_point())
print('dtype',quantized_tensor.dtype)

is float_tensor quantized?
False

is quantized_tensor quantized?
True

 tensor details
tensor([1., 2., 3.], size=(3,), dtype=torch.quint8,
       quantization_scheme=torch.per_tensor_affine, scale=0.1, zero_point=0)
scale 0.1
zero point: 0
dtype torch.quint8


In [10]:
#Tensor.is_meta

# this property checks whether a tensor is a meta tensor
# meta tensors are special tensors that do not allocate memory for their data and are used primarlyy for shape and metadata inference without storing actual values

import torch 

regular_tensor = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float32)
print('si regular_tensor a meta tensor?')
print(regular_tensor.is_meta)

meta_tensor = torch.empty(3, dtype=torch.float32, device='meta')
print('\n is meta_tenosr a meta tensor?')
print(meta_tensor.is_meta)

print# Print details of the meta tensor
print("\nMeta Tensor Details:")
print("Shape:", meta_tensor.shape)
print("Dtype:", meta_tensor.dtype)
print("Device:", meta_tensor.device)

# Attempt to access data from the meta tensor (will raise an error)
try:
    print("\nAccessing data from meta_tensor:")
    print(meta_tensor[0])  # This will raise an error
except RuntimeError as e:
    print("Error:", e)

si regular_tensor a meta tensor?
False

 is meta_tenosr a meta tensor?
True

Meta Tensor Details:
Shape: torch.Size([3])
Dtype: torch.float32
Device: meta

Accessing data from meta_tensor:
tensor(..., device='meta', size=())
