In [ ]:
import torch 
base_tensor = torch.rand(4,4)
print("Base Tensor:")
print(base_tensor)

view_tensor = base_tensor.view(2,8)
print('\nView Tensor (reshaped to 2x8)')
print(view_tensor)

print('\n Do `base_tensor` and `view_tensor` share the same data')
print(base_tensor.storage.epoch().data_ptr() == view_tensor.storage().data_ptr())

view_tensor[0][0] = 3.14
print('\n after modifying the view tensor:')
print('view tensr:')
print(view_tensor)
print('base tensor (reflects the change:)')
print(base_tensor)

non_contiguous_tensor = base_tensor.transpose(0,1)
print('\nTranposed Tensor (non-contiguous):')
print(non_contiguous_tensor)
print('is the transposed tenser contiguos?')
print(non_contiguous_tensor)

contiguous_tensor = non_contiguous_tensor.contiguos()
print('\nContiguous Tensor (after calling `.contiguous()`):')
print(contiguous_tensor)
print('Is the new tensor contiguous?')
print(contiguous_tensor.is_contiguous())

Base Tensor:
tensor([[0.0569, 0.4049, 0.2065, 0.2408],
        [0.8231, 0.6954, 0.0018, 0.7668],
        [0.3474, 0.5443, 0.5155, 0.7470],
        [0.1728, 0.7847, 0.6770, 0.3676]])

View Tensor (reshaped to 2x8):
tensor([[0.0569, 0.4049, 0.2065, 0.2408, 0.8231, 0.6954, 0.0018, 0.7668],
        [0.3474, 0.5443, 0.5155, 0.7470, 0.1728, 0.7847, 0.6770, 0.3676]])

Do `base_tensor` and `view_tensor` share the same data?
True

After modifying the view tensor:
View Tensor:
tensor([[3.1400e+00, 4.0494e-01, 2.0647e-01, 2.4084e-01, 8.2310e-01, 6.9536e-01,
         1.8490e-03, 7.6678e-01],
        [3.4742e-01, 5.4429e-01, 5.1549e-01, 7.4701e-01, 1.7281e-01, 7.8473e-01,
         6.7705e-01, 3.6760e-01]])
Base Tensor (reflects the change):
tensor([[3.1400e+00, 4.0494e-01, 2.0647e-01, 2.4084e-01],
        [8.2310e-01, 6.9536e-01, 1.8490e-03, 7.6678e-01],
        [3.4742e-01, 5.4429e-01, 5.1549e-01, 7.4701e-01],
        [1.7281e-01, 7.8473e-01, 6.7705e-01, 3.6760e-01]])

Transposed Tensor (non-conti

C:\Users\fadzw\AppData\Local\Temp\ipykernel_23872\844185944.py:15: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  print(base_tensor.storage().data_ptr() == view_tensor.storage().data_ptr())  # Output: True


In [17]:
import torch 

tensor = torch.arange(24).reshape(2,3,4)
print('base tensor:')
print(tensor)

#sparse tensor for indices() example 
indices = torch.tensor([[0,1],[1,2]])
values = torch.tensor([3.0,4.0])
sparse_tensor = torch.sparse_coo_tensor(indices, values, size=(3,3))

#1. adjoint() (Alias for .mH)
# print('\nAdjoint (Conjugate Transpose):',tensor.adjoint())

#2. as_strided()
# print('\nas_strided():',torch.as_strided(tensor, size=(2,6), stride=(12,1)))

#3.0 detach()
# print('\ndetach():',tensor.detach())

#4.0 diagonal()
# print('\ndiagonal():',tensor.diagonal(offset=0, dim1=1, dim2=2))

# 5.0 expand()
# print('expand()',tensor.expand(3,2,3,4))

# 6. expand_as()
# other_tensor = torch.zeros(3,2,3,4)
# print('expand_as()',tensor.expand_as(other_tensor))

# # 7.0 movedim()
# print('\nmovedim():',(torch.movedim(tensor, source=0, destination=-1)).shape)

# # 8.0 narrow()
# print('\nnarrow():',tensor.narrow(dim=1, start=1, length=2))

# #9.0 permute()
# print('\npermute():', (tensor.permute(2,0,1)).shape)

# # 10 select()
# print('\nselect():',tensor.select(dim=0,index=1))

# # 11. squeeze()
# print('\nsqueeze()',tensor.squeeze())

# # 12. tranpose()
# print('\ntranpose', (tensor.transpose(1,2)).shape)

# # 13. t() Transfopose for 2D tensors
# two_d_tensor = torch.rand(3,4)
# print('\nt():',two_d_tensor.t())

# # 14 T (property for transpose)
# print('\nT (property):',two_d_tensor.T.shape)

# # 15. H (Conjugate transpose for complex tensors)
complex_tensor = torch.tensor([[1 + 2j, 3 + 4j], [5 + 6j, 7 + 8j]], dtype=torch.cfloat)
# print('\n H (Hermitian/Conjugate transpose):', complex_tensor.H)

# # 16 mT (Matrix transpose property)
# print('\nmT (matrix transpose):', complex_tensor.mT)

# # 17 mH (Matrix Hermitian/conjugate transpose property)
# print('\nmH matrix hermitian', complex_tensor.mH)

# # 18. real 19. imag
# print('\nReal Part:', complex_tensor.real, '\nImage Part:', complex_tensor.imag)

# # 20 view_as_real
# print('\nview_as_real():',torch.view_as_real(complex_tensor))

# # 21 unflatten
# print('\nunflatten',(tensor.unflatten(dim=1, sizes=(1,3))).shape)

# # 22 unfold()
# print('\nunfold',(tensor.unfold(dimension=2, size=2, step=1)).shape)

# # 23 unsquueze
# print('\nunsqueeze():', tensor.unsqueeze(dim=0))

# # 24 view()
# print('\nview():',tensor.view(2,-1))

# #25 view_as()
# other_tensor_view = torch.zeros(2,12)
# print('\nview_as():', (tensor.view_as(other_tensor_view)).shape)

# #26 unbind()
# print('\nunbind():',torch.unbind(tensor,dim=0))
# for i,t in enumerate((torch.unbind(tensor,dim=0))):
#     print(f'Tensor {i}: {t}')

#27 split()
# split_tensor = torch.split(tensor,split_size_or_sections=2,dim=1)
# print('\nsplit():')
# for i,t in enumerate(split_tensor):
#     print(f'H-Slit {i} : {t.shape}')


#27 split()
# split_tensors = torch.split(tensor, split_size_or_sections=2, dim=1)
# print("\nsplit():")
# for i, t in enumerate(split_tensors):
#     print(f"Split {i}: {t.shape}")

#28 hsplit()
# hsplit_tensors = torch.hsplit(tensor,2)
# print('\nhsplit():')
# for i,t in enumerate(hsplit_tensors):
#     print(f'H-split {i}: {t.shape}')

#29 vsplit()
# vsplit_tensors = torch.vsplit(tensor, 2)
# print("\nvsplit():")
# for i, t in enumerate(vsplit_tensors):
#     print(f"V-Split {i}: {t.shape}")

#30 tensor_split()
# tensor_split_tensors = torch.tensor_split(tensor, indices_or_sections=2, dim=1)
# print('\ntensor_split():')
# for i,t in enumerate(tensor_split_tensors):
#     print(f'Teensor Split: {i}:{t.shape}')

#31 split_with_sizes()
# split_with_sizes_tensors = torch.split_with_sizes(tensor,split_sizes=[1,2],dim=1)
# print('\nsplit_with_sizes():')
# for i,t in enumerate(split_with_sizes_tensors):
#     print(f'split with sizes {i}: {t.shape}')

#32 swapaxes()
# swapped_axes_tensor = torch.swapaxes(tensor, axis0=1, axis1=2)
# print('\nswapaxes():')
# print(swapped_axes_tensor.shape)

#swapdims()
# swapped_dims_tensor = torch.swapdims(tensor, dim0=1,dim1=2)
# print('\nswapdims():')
# print(swapped_dims_tensor)

#34. chunk
# chunk_tensors = torch.chunk(tensor, chunks=2, dim=1)
# print('\nchunk():')
# for i,t in enumerate(chunk_tensors):
#     print(f'chunk {i}: {t.shape}')

#35. indices() (Sparse Tennsor Only)
# sparse_indices = sparse_tensor.indices()
# print("\nindices() (Sparse Tensor):")
# print(sparse_indices)


base tensor:
tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
