In [ ]:
#https://pytorch.org/docs/stable/nn.functional.html

In [ ]:
#transpose1d 

#applies a 1D transposed convolution to an input signal

import torch 
import torch.nn.functional as F 

inputs = torch.randn(2,16,50) 
weights = torch.randn(16,33,5)

bias = torch.rand(33)

output = F.conv_transpose1d(
    input = inputs,
    weight = weights,
    bias = bias,
    stride = 2,
    padding = 1,
    output_padding=1,
    groups=1,
    dilation=1
)

print('Input shape:',inputs.shape)
print('Weight shape:', weights.shape)
print('Bias shape:', bias.shape)
print('Output shape:', output.shape)

Input shape: torch.Size([2, 16, 50])
Weight shape: torch.Size([16, 33, 5])
Bias shape: torch.Size([33])
Output shape: torch.Size([2, 33, 102])


In [2]:
#transpose2d

#applies 2d transposed convolution to an input image. 
# Transposed convolutions are commonly used in tasks like upsampling image generation and semantic segmentations

import torch 
import torch.nn as nn

# batch_size = 1, in_channels = 4 , h = 5 w =5
inputs = torch.randn(1,4,5,5)

# in_channel = 4 , out_channels = 8 kernel_height = 3, kernel_width = 3
weights = torch.randn( 4, 8, 3,3)
bias = torch.randn(8)

output = F.conv_transpose2d(
    input = inputs,
    weight = weights,
    bias = bias,
    stride = 2,
    padding = 1,
    output_padding = 1,
    groups = 1,
    dilation =1
)

print('Input shape:',inputs.shape)
print('Weight shape:',weights.shape)
print('Bias shape:',bias.shape)
print('Output shape:', output.shape)


Input shape: torch.Size([1, 4, 5, 5])
Weight shape: torch.Size([4, 8, 3, 3])
Bias shape: torch.Size([8])
Output shape: torch.Size([1, 8, 10, 10])


In [3]:
#transpose3d 

#function applies a 3d transposed convolution to a 3d tensor
#transposed convolutions in 3d are commonly used in tasks like volumetric upsamping ,medical imagin and video processing

import torch 
import torch.nn.functional as F

# define input tensor
    # batch_size = 2 , in_channels = 16, depth = 50, kernel_height =3, kernel_widht = 3
inputs = torch.randn(2,16,50,10,20) 

#define weight tensor
    #in_channels = 16, out_channels =33, kernel_depth=3, kernel_height=3, kernel_width =3
weights = torch.randn(16,33,3,3,3)

bias = torch.randn(33) #define optional bias tensor (Out_channel = 33)

output = F.conv_transpose3d(
    input=inputs,
    weight=weights,
    bias = bias,
    stride =2, #stride of the conv
    padding = 1,
    output_padding =1,
    groups = 1,
    dilation =1 #dilation rate
)

print('Input shaoe:',inputs.shape)
print('Weight shape:',weights.shape)
print('Bias shape:', bias.shape)
print('Output shape:', output.shape)

Input shaoe: torch.Size([2, 16, 50, 10, 20])
Weight shape: torch.Size([16, 33, 3, 3, 3])
Bias shape: torch.Size([33])
Output shape: torch.Size([2, 33, 100, 20, 40])


In [ ]:
#http://turbolearn.ai/

In [ ]:
#unfold 

# function extracts sliding local bloacls from batched input tensor
# this is commonly used in tasks like convolutional neural networks where you need to extract small regions of an image for processing

import torch 
import torch.nn.functional as F 

#define a 4d input
    # batch_size = 1 , channels =3, height = 4, width =4
input_tensor = torch.arange(48, dtype=torch.float32).reshape(1,3,4,4)
print('Input Tensor Shape:', input_tensor.shape)
print('Input Tensor:\n', input_tensor)

#parameters for the unfold operation
kernel_size = (2,2)
stride = 1
padding = 0
dilation = 1

unfolded = F.unfold(input=input_tensor, kernel_size = kernel_size, stride=stride, padding=padding, dilation=dilation)

#print the unfolder tensor
print('\n Unfolder Tensor Shape:',unfolded.shape)
print('Unfolded Tensor:\n', unfolded)

#fold
#Optinaly , fold the tensor back to its original shape
#it aggragtes overlapping patches using summation by default
folded = F.fold(input=unfolded, output_size=(4,4),kernel_size=kernel_size, padding=padding, dilation=dilation)
print('\nFolded Tensor Shape:', folded.shape)
print('Folded Tensor:\n', folded)

Input Tensor Shape: torch.Size([1, 3, 4, 4])
Input Tensor:
 tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]],

         [[16., 17., 18., 19.],
          [20., 21., 22., 23.],
          [24., 25., 26., 27.],
          [28., 29., 30., 31.]],

         [[32., 33., 34., 35.],
          [36., 37., 38., 39.],
          [40., 41., 42., 43.],
          [44., 45., 46., 47.]]]])

 Unfolder Tensor Shape: torch.Size([1, 12, 9])
Unfolded Tensor:
 tensor([[[ 0.,  1.,  2.,  4.,  5.,  6.,  8.,  9., 10.],
         [ 1.,  2.,  3.,  5.,  6.,  7.,  9., 10., 11.],
         [ 4.,  5.,  6.,  8.,  9., 10., 12., 13., 14.],
         [ 5.,  6.,  7.,  9., 10., 11., 13., 14., 15.],
         [16., 17., 18., 20., 21., 22., 24., 25., 26.],
         [17., 18., 19., 21., 22., 23., 25., 26., 27.],
         [20., 21., 22., 24., 25., 26., 28., 29., 30.],
         [21., 22., 23., 25., 26., 27., 29., 30., 31.],
         [32., 33., 34., 36., 37., 

In [6]:
#avg_pool1d

# applies 1d average pooling over an input singal
# used in tasks like time series analysis or audio processing 

import torch
import torch.nn.functional as F 

#define a 3d input tensor 
    #batch_size = 1, channels = 1, length =7
input_tensor = torch.tensor([[1,2,3,4,5,6,7]], dtype = torch.float32)

print('Input Tensor Shape:', input_tensor.shape)
print('Input Tensor:\n',input_tensor)

kernel_size = 3,
stride = 2
padding = 0
ceil_mode = False
count_include_pad = True 

#aaply 1d average pooling 
output = F.avg_pool1d(
    input = input_tensor,
    kernel_size = kernel_size,
    stride = stride ,
    padding = padding,
    ceil_mode = ceil_mode,
    count_include_pad = count_include_pad
)

print('\nOutput Tensor Shape:', output.shape)
print('Output Tensor:\n', output)

Input Tensor Shape: torch.Size([1, 7])
Input Tensor:
 tensor([[1., 2., 3., 4., 5., 6., 7.]])

Output Tensor Shape: torch.Size([1, 3])
Output Tensor:
 tensor([[2., 4., 6.]])


In [11]:
#torch.nn.functional.avg_pool2d 

# function applies 2d average pooling over an input image or feature map
# commonly used in CNN for downsampling

import torch 
import torch.nn.functional as F

#define 4d input tensor
    #batch_size =1, channels=1, height=6, width=6
input_tensor = torch.arange(36, dtype=torch.float32).reshape(1, 1, 6, 6)
print("Input Tensor Shape:", input_tensor.shape)
print("Input Tensor:\n", input_tensor)

# Parameters for the avg_pool2d operation
kernel_size = (2, 2)  # Size of the pooling window
stride = (2, 2)       # Stride of the pooling window
padding = 0           # Padding added to the input
ceil_mode = False     # Use floor instead of ceil to compute output size
count_include_pad = True  # Include zero-padding in averaging calculation
divisor_override = None   # Use the default divisor (pooling region size)

# Apply 2D average pooling
output = F.avg_pool2d(
    input=input_tensor,
    kernel_size=kernel_size,
    stride=stride,
    padding=padding,
    ceil_mode=ceil_mode,
    count_include_pad=count_include_pad,
    divisor_override=divisor_override
)

# Print the output tensor
print("\nOutput Tensor Shape:", output.shape)
print("Output Tensor:\n", output)



Input Tensor Shape: torch.Size([1, 1, 6, 6])
Input Tensor:
 tensor([[[[ 0.,  1.,  2.,  3.,  4.,  5.],
          [ 6.,  7.,  8.,  9., 10., 11.],
          [12., 13., 14., 15., 16., 17.],
          [18., 19., 20., 21., 22., 23.],
          [24., 25., 26., 27., 28., 29.],
          [30., 31., 32., 33., 34., 35.]]]])

Output Tensor Shape: torch.Size([1, 1, 3, 3])
Output Tensor:
 tensor([[[[ 3.5000,  5.5000,  7.5000],
          [15.5000, 17.5000, 19.5000],
          [27.5000, 29.5000, 31.5000]]]])


In [5]:

#torch.nn.functional.avg_pool3d

# apples 3d average pooling over a volumetirc input tensor
# commonly used in tasks like medical imaging

import torch
import torch.nn.functional as F 

input_tensor = torch.arange(64, dtype=torch.float32).reshape(1,1,4,4,4)
print('Input Tensor Shape:', input_tensor.shape)
print('Input Tensor:', input_tensor)

#parameters for the avg_pool2d operation
kernel_size = (2,2,2) #size of the pooling window
stride = (2,2,2) #stride of the pooling window 
padding = 0 #padding added to the input
ceil_mode = False  #use floor instead of ceil to compute output size
count_include_pad = True #include zero-padding in averaging calculation
divisor_override = None  #use the default divisor (pooling region size)

#apply 3d average pooling
output = F.avg_pool3d(
    input = input_tensor,
    kernel_size=kernel_size,
    stride=stride,
    padding=padding,
    ceil_mode=ceil_mode,
    count_include_pad=count_include_pad,
    divisor_override=divisor_override
)

#print the output tensor
print('\n OUtput Tensor Shape:', output.shape)
print('Output Tensor:', output)

# For each pooling window, the average of the values inside the window is computed.
# The output shape depends on the input shape, kernel size, stride, and padding.


Input Tensor Shape: torch.Size([1, 1, 4, 4, 4])
Input Tensor: tensor([[[[[ 0.,  1.,  2.,  3.],
           [ 4.,  5.,  6.,  7.],
           [ 8.,  9., 10., 11.],
           [12., 13., 14., 15.]],

          [[16., 17., 18., 19.],
           [20., 21., 22., 23.],
           [24., 25., 26., 27.],
           [28., 29., 30., 31.]],

          [[32., 33., 34., 35.],
           [36., 37., 38., 39.],
           [40., 41., 42., 43.],
           [44., 45., 46., 47.]],

          [[48., 49., 50., 51.],
           [52., 53., 54., 55.],
           [56., 57., 58., 59.],
           [60., 61., 62., 63.]]]]])

 OUtput Tensor Shape: torch.Size([1, 1, 2, 2, 2])
Output Tensor: tensor([[[[[10.5000, 12.5000],
           [18.5000, 20.5000]],

          [[42.5000, 44.5000],
           [50.5000, 52.5000]]]]])


In [ ]:
#torch.nn.functional.max_pool1d

# apples 1d max pooling over an input signal, which is commonly used in task like time series analysis or audio processing
# max pooling extracts the maximum value from each sliding window
# reducint the dimensionality of the input while preserving important features

import torch 
import torch.nn.functional as F 

input_tensor = torch.tensor([[1,3,5,6,9,2,4]], dtype=torch.float32)
print('Input Tensor Shape:',input_tensor.shape)
print('Input Tensor:\n', input_tensor)

kernel_size = 3
stride = 2
padding = 0
dilation = 1
ceil_mode = False 
return_indices = True 

#apply 1d max pooling
output, indices = F.max_pool1d(
    input=input_tensor,
    kernel_size=kernel_size,
    stride=stride,
    padding=padding,
    dilation=dilation,
    ceil_model=ceil_mode,
    return_indices=return_indices
)

#print the output tensor and indices
print('\nOutput Tensor Shape:',output.shape)
print('Output Tensor (Max Values):\n',output)
print('Indices of Max Values:\n',indices)

Input Tensor Shape: torch.Size([1, 1, 4, 4, 4])
Input Tensor:
 tensor([[[[[ 0.,  1.,  2.,  3.],
           [ 4.,  5.,  6.,  7.],
           [ 8.,  9., 10., 11.],
           [12., 13., 14., 15.]],

          [[16., 17., 18., 19.],
           [20., 21., 22., 23.],
           [24., 25., 26., 27.],
           [28., 29., 30., 31.]],

          [[32., 33., 34., 35.],
           [36., 37., 38., 39.],
           [40., 41., 42., 43.],
           [44., 45., 46., 47.]],

          [[48., 49., 50., 51.],
           [52., 53., 54., 55.],
           [56., 57., 58., 59.],
           [60., 61., 62., 63.]]]]])

Output Tensor Shape: torch.Size([1, 1, 2, 2, 2])
Output Tensor:
 tensor([[[[[10.5000, 12.5000],
           [18.5000, 20.5000]],

          [[42.5000, 44.5000],
           [50.5000, 52.5000]]]]])


In [1]:
#torch.nn.functional.max_pool2d

# fuction apples 2d max pooling over an input tensor which is commonly used in CNN for downsampling feature mapes while preserving the most significant features
import torch 
import torch.nn.functional as F

input_tensor = torch.arange(36,dtype=torch.float32).reshape(1,1,6,6)
print('Input Tensor Shape:', input_tensor.shape)
print('Input Tensor:', input_tensor)

#parameters for the max_pool2d operation
kernel_size = (2,2)
stride = (2,2)
padding = 0
dilation = 1
ceil_mode = False 
return_indices = True

output, indices = F.max_pool2d(
    input=input_tensor,
    kernel_size=kernel_size,
    stride=stride,
    padding=padding,
    dilation=dilation,
    ceil_mode=ceil_mode,
    return_indices=return_indices
)

print('\nOutput Tensor Shape:',output.shape)
print('Output Tensor (Max values):\n',output)
print('Indices of Max Values:\n',indices)

# for each pooling window, the maxium value is extracted 
# if return_indices=True, the indices of the maximum values are also returned

Input Tensor Shape: torch.Size([1, 1, 6, 6])
Input Tensor: tensor([[[[ 0.,  1.,  2.,  3.,  4.,  5.],
          [ 6.,  7.,  8.,  9., 10., 11.],
          [12., 13., 14., 15., 16., 17.],
          [18., 19., 20., 21., 22., 23.],
          [24., 25., 26., 27., 28., 29.],
          [30., 31., 32., 33., 34., 35.]]]])

Output Tensor Shape: torch.Size([1, 1, 3, 3])
Output Tensor (Max values):
 tensor([[[[ 7.,  9., 11.],
          [19., 21., 23.],
          [31., 33., 35.]]]])
Indices of Max Values:
 tensor([[[[ 7,  9, 11],
          [19, 21, 23],
          [31, 33, 35]]]])


In [1]:
#max_pool3d

# function applies 3d max pooling over a volumetric input tensor which iscommonly used in tasks like medical imaging or video processing. max pooling extracts the maxium value from each sliding window reducing the dimensionality of the input while preserving important faetures

import torch 
import torch.nn.functional as F 
#define a 5D input tensor
    # batch_size = 1, channels = 1, depth = 4, height = 4, width = 4
input_tensor = torch.arange(64, dtype=torch.float32).reshape(1,1,4,4,4)
print('Input Tensor Shape:',input_tensor.shape)
print('Input Tensor:\n', input_tensor)

#parameters for the max_pool3d operation
kernel_size = (2,2,2) #size of the poolingwindow
stride = (2,2,2) #stride of the pooling window
padding= 0
dilation = 1
ceil_mode = False 
return_indices = True

output , indices = F.max_pool3d(
    input=input_tensor,
    kernel_size = kernel_size,
    stride=stride,
    padding=padding,
    dilation=dilation,
    ceil_mode=ceil_mode,
    return_indices=return_indices
)

print('\n Output Tensor Shape:', output.shape)
print('Output Tensor (Max Values):\n',output)
print('Indices of Max Values:\n',indices)


Input Tensor Shape: torch.Size([1, 1, 4, 4, 4])
Input Tensor:
 tensor([[[[[ 0.,  1.,  2.,  3.],
           [ 4.,  5.,  6.,  7.],
           [ 8.,  9., 10., 11.],
           [12., 13., 14., 15.]],

          [[16., 17., 18., 19.],
           [20., 21., 22., 23.],
           [24., 25., 26., 27.],
           [28., 29., 30., 31.]],

          [[32., 33., 34., 35.],
           [36., 37., 38., 39.],
           [40., 41., 42., 43.],
           [44., 45., 46., 47.]],

          [[48., 49., 50., 51.],
           [52., 53., 54., 55.],
           [56., 57., 58., 59.],
           [60., 61., 62., 63.]]]]])

 Output Tensor Shape: torch.Size([1, 1, 2, 2, 2])
Output Tensor (Max Values):
 tensor([[[[[21., 23.],
           [29., 31.]],

          [[53., 55.],
           [61., 63.]]]]])
Indices of Max Values:
 tensor([[[[[21, 23],
           [29, 31]],

          [[53, 55],
           [61, 63]]]]])


In [2]:
#max_unpool1d,
#perform the inverse operation of max_pool1d, reconstructing the orignal input tensor from the pooled output and indices returned by max_pool1d
# requre outou from a previos=is max_pool1d operation , including both the pooled vauues and the indices of the maximum values

import torch 
import torch.nn.functional as F 

#define a 3d input tensor
input_tensor = torch.tensor([[1,3,5,7,9,2,4]], dtype=torch.float32)
print('Input Tensor Shape:', input_tensor.shape)
print('Input Tensor:\n',input_tensor)

#parameters for max_pool1d
kernel_size = 3
stride = 2
padding = 0
return_indices = True 

pooled_output, indices = F.max_pool1d(
    input=input_tensor,
    kernel_size=kernel_size,
    stride=stride,
    padding=padding,
    return_indices=return_indices
)

print('\nPooled Output Shape:',pooled_output.shape)
print('Pooled Output:\n',pooled_output)
print('Indices of Max Values:\n', indices)

output_size = (1,1,7)

unpooled_output = F.max_unpool1d(
    input = pooled_output,
    indices = indices,
    kernel_size=kernel_size,
    stride=stride,
    padding=padding,
    output_size=output_size
)


print('\n Unnpooled Output Shape:', unpooled_output.shape)
print('Unpooled Output:\n', unpooled_output)


Input Tensor Shape: torch.Size([1, 7])
Input Tensor:
 tensor([[1., 3., 5., 7., 9., 2., 4.]])

Pooled Output Shape: torch.Size([1, 3])
Pooled Output:
 tensor([[5., 9., 9.]])
Indices of Max Values:
 tensor([[2, 4, 4]])

 Unnpooled Output Shape: torch.Size([1, 7])
Unpooled Output:
 tensor([[0., 0., 5., 0., 9., 0., 0.]])


In [3]:
#max_unpool2d

# this function performs the inver operation of max_pool2d, reconstructing the original input tensor form the pooled output and the indices returned by max_pool2d

import torch 
import torch.nn.functional as F

input_tensor = torch.arange(36, dtype=torch.float32).reshape(1,1,6,6)
print('Input Tensor Shape:', input_tensor.shape)
print('Input Tensor:\n', input_tensor)

kernel_size = (2,2)
stride = (2,2)
padding = 0
return_indices = True 

pooled_output, indices = F.max_pool2d(
    input = input_tensor,
    kernel_size = kernel_size,
    stride =stride,
    padding = padding,
    return_indices=return_indices
)

print('\nPooled Output Shape:', pooled_output.shape)
print('Pooled Output:\n',pooled_output)
print('Indices of Max Values:\n',indices)

output_size = (1,1,6,6)

#apply 2d max unpooling
unpooled_output = F.max_unpool2d(
    input = pooled_output,
    indices = indices,
    kernel_size = kernel_size,
    stride=stride,
    padding=padding,
    output_size=output_size
)

print('\nUnpooled Output Shape:', unpooled_output.shape)
print('Unpooled Output:\n', unpooled_output)


Input Tensor Shape: torch.Size([1, 1, 6, 6])
Input Tensor:
 tensor([[[[ 0.,  1.,  2.,  3.,  4.,  5.],
          [ 6.,  7.,  8.,  9., 10., 11.],
          [12., 13., 14., 15., 16., 17.],
          [18., 19., 20., 21., 22., 23.],
          [24., 25., 26., 27., 28., 29.],
          [30., 31., 32., 33., 34., 35.]]]])

Pooled Output Shape: torch.Size([1, 1, 3, 3])
Pooled Output:
 tensor([[[[ 7.,  9., 11.],
          [19., 21., 23.],
          [31., 33., 35.]]]])
Indices of Max Values:
 tensor([[[[ 7,  9, 11],
          [19, 21, 23],
          [31, 33, 35]]]])

Unpooled Output Shape: torch.Size([1, 1, 6, 6])
Unpooled Output:
 tensor([[[[ 0.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  7.,  0.,  9.,  0., 11.],
          [ 0.,  0.,  0.,  0.,  0.,  0.],
          [ 0., 19.,  0., 21.,  0., 23.],
          [ 0.,  0.,  0.,  0.,  0.,  0.],
          [ 0., 31.,  0., 33.,  0., 35.]]]])


In [4]:
#max_unpool3d 

# inverse operation of max_pool3d, reconstructing input tensor form the pooled output and indics retuned by max_pool3d
# function requires the outpu of a prevois max_pool3d, including both the pooled values and indices of the maximum values.

import torch 
import torch.nn.functional as F

input_tensor = torch.arange(64, dtype=torch.float32).reshape(1,1,4,4,4)
print('Input Tensor Shape:', input_tensor.shape)
print('Input Tensor:\n', input_tensor)

kernel_size = (2,2,2)
stride = (2,2,2)
padding = 0
return_indices = True 

pooled_output, indices = F.max_pool3d(
    input = input_tensor,
    kernel_size = kernel_size,
    stride =stride,
    padding =padding,
    return_indices=return_indices
)


print('\nPooled Output SHape:', pooled_output.shape)
print('Pooled Output:\n', pooled_output)
print('Indices of Max Values:\n', indices)

output_size = (1,1,4,4,4)

unpooled_output = F.max_unpool3d(
    input=pooled_output,
    indices=indices,
    kernel_size=kernel_size,
    stride=stride,
    padding=padding,
    output_size=output_size
)

print('\nUnpooled Output Shape:', unpooled_output.shape)
print('Unpooled Output:\n', unpooled_output)

Input Tensor Shape: torch.Size([1, 1, 4, 4, 4])
Input Tensor:
 tensor([[[[[ 0.,  1.,  2.,  3.],
           [ 4.,  5.,  6.,  7.],
           [ 8.,  9., 10., 11.],
           [12., 13., 14., 15.]],

          [[16., 17., 18., 19.],
           [20., 21., 22., 23.],
           [24., 25., 26., 27.],
           [28., 29., 30., 31.]],

          [[32., 33., 34., 35.],
           [36., 37., 38., 39.],
           [40., 41., 42., 43.],
           [44., 45., 46., 47.]],

          [[48., 49., 50., 51.],
           [52., 53., 54., 55.],
           [56., 57., 58., 59.],
           [60., 61., 62., 63.]]]]])

Pooled Output SHape: torch.Size([1, 1, 2, 2, 2])
Pooled Output:
 tensor([[[[[21., 23.],
           [29., 31.]],

          [[53., 55.],
           [61., 63.]]]]])
Indices of Max Values:
 tensor([[[[[21, 23],
           [29, 31]],

          [[53, 55],
           [61, 63]]]]])

Unpooled Output Shape: torch.Size([1, 1, 4, 4, 4])
Unpooled Output:
 tensor([[[[[ 0.,  0.,  0.,  0.],
           [ 0.,  

In [ ]:
#1p_pool1d 

#function applies 1d power-average pooling operation over an input signal.
# the 'power-average' is computed as the Lp-norm of the values in each pooling window.
import torch 
import torch.nn.functional as F 

input_tensor = torch.tensor([[[1.0,2.0,3.0,4.0,5.0,6.0]]],dtype=torch.float32)
print('Input tensor shape:', input_tensor.shape)
print('input tensor:\n', input_tensor)

norm_type = 2.0
kernel_size = 3
stride = 2 
ceil_mode = False 

output = F.lp_pool1d(
    input = input_tensor,
    norm_type=norm_type,
    kernel_size=kernel_size,
    stride=stride,
    ceil_mode=ceil_mode
)


print('\nOutput Tensor Shape:', output.shape)
print('Output Tensor"\n', output)

Input tensor shape: torch.Size([1, 1, 6])
input tensor:
 tensor([[[1., 2., 3., 4., 5., 6.]]])

Output Tensor Shape: torch.Size([1, 1, 2])
Output Tensor"
 tensor([[[3.7417, 7.0711]]])


In [3]:
#1l_pool2d 
# function applies a 2d power-average pooling opration over an input tensor 
# the power-average is computed as the Lp norm of the value sin each pooling wind

import torch 
import torch.nn.functional as F 

input_tensor = torch.arange(36, dtype=torch.float32).reshape(1,1,6,6)
print('input tensor shape',input_tensor.shape)
print('input tensor', input_tensor)

norm_type = 2.0 
kernel_size = (2,2)
stride = (2,2)
ceil_mode = False 

output = F.lp_pool2d(
    input = input_tensor,
    norm_type = norm_type,
    kernel_size = kernel_size,
    stride = stride, 
    ceil_mode = ceil_mode
)

print('\nOutput Tensor Shape:', output.shape)
print('Output Tensor:\n', output)

input tensor shape torch.Size([1, 1, 6, 6])
input tensor tensor([[[[ 0.,  1.,  2.,  3.,  4.,  5.],
          [ 6.,  7.,  8.,  9., 10., 11.],
          [12., 13., 14., 15., 16., 17.],
          [18., 19., 20., 21., 22., 23.],
          [24., 25., 26., 27., 28., 29.],
          [30., 31., 32., 33., 34., 35.]]]])

Output Tensor Shape: torch.Size([1, 1, 3, 3])
Output Tensor:
 tensor([[[[ 9.2736, 12.5698, 16.1864],
          [31.5911, 35.5246, 39.4715],
          [55.3353, 59.3127, 63.2930]]]])


In [4]:
#lp_pool3d
# function applies a 3d power-average pooling operation over an input tensor.
# the power-average is computed as the Lp-norm of the values in each pooling window.

import torch 
import torch.nn.functional as F 

input_tensor = torch.arange(64, dtype=torch.float32).reshape(1,1,4,4,4)
print('Input Tensor Shape',input_tensor.shape)
print('Input Tensor:', input_tensor)

norm_type = 2.0 
kernel_size = (2,2,2)
stride = (2,2,2)
ceil_mode = False 

output = F.lp_pool3d(
    input = input_tensor,
    norm_type = norm_type,
    kernel_size = kernel_size,
    ceil_mode = ceil_mode
)

print('\n Output Tensor Shape:', output.shape)
print('Output Tensor:', output)

Input Tensor Shape torch.Size([1, 1, 4, 4, 4])
Input Tensor: tensor([[[[[ 0.,  1.,  2.,  3.],
           [ 4.,  5.,  6.,  7.],
           [ 8.,  9., 10., 11.],
           [12., 13., 14., 15.]],

          [[16., 17., 18., 19.],
           [20., 21., 22., 23.],
           [24., 25., 26., 27.],
           [28., 29., 30., 31.]],

          [[32., 33., 34., 35.],
           [36., 37., 38., 39.],
           [40., 41., 42., 43.],
           [44., 45., 46., 47.]],

          [[48., 49., 50., 51.],
           [52., 53., 54., 55.],
           [56., 57., 58., 59.],
           [60., 61., 62., 63.]]]]])

 Output Tensor Shape: torch.Size([1, 1, 2, 2, 2])
Output Tensor: tensor([[[[[ 37.7889,  42.3792],
           [ 57.3062,  62.5140]],

          [[122.4582, 128.0156],
           [144.7342, 150.3197]]]]])


In [5]:
# adaptive_max_pool1d 
# function applies 1d adaptive max pooling which dynamically adjusts the size of the pooling window to produce a fixed output size. It is particularly useful when you need a specific output size regardless of the input size 

import torch 
import torch.nn.functional as F 

input_tensor = torch.tensor([[[1.0,2.0,3.0,4.0,5.0,6.0,7.0]]], dtype=torch.float32)
print('Input Tensor Shape:', input_tensor.shape)
print('Input Tensor:\n', input_tensor)

output_size = 3
return_indices = True

output, indices = F.adaptive_max_pool1d(
    input = input_tensor,
    output_size = output_size, 
    return_indices = return_indices
)

print('\nOutput Tensor Shape:', output.shape)
print('Output Tensor (Max Values):\n', output)
print('Indices of Max Values:\n', indices)



Input Tensor Shape: torch.Size([1, 1, 7])
Input Tensor:
 tensor([[[1., 2., 3., 4., 5., 6., 7.]]])

Output Tensor Shape: torch.Size([1, 1, 3])
Output Tensor (Max Values):
 tensor([[[3., 5., 7.]]])
Indices of Max Values:
 tensor([[[2, 4, 6]]])


In [ ]:
#max_pool2d 
# applies 2d adaptive max pooling, dynamically adjusts the size of the pooling windows to produce 
# a fixed output size , it is particularly useful when you need a specific output size regardless of the input size

import torch 
import torch.nn.functional as F 

input_tensor = torch.arange(36, dtype=torch.float32).reshape(1,1,6,6)
print('Input Tensor Shape', input_tensor.shape)
print('Input Tensor', input_tensor)

output_size = (3,3)
return_indices = True 

output, indices = F.adaptive_max_pool2d(
    input = input_tensor,
    output_size = output_size,
    return_indices = return_indices
)

print('\nOutput Tensor Shape:',output.shape)
print('Output Tensor (Max Values)',output)
print('Indices of Max Values:\n',indices)

Input Tensor Shape torch.Size([1, 1, 6, 6])
Input Tensor tensor([[[[ 0.,  1.,  2.,  3.,  4.,  5.],
          [ 6.,  7.,  8.,  9., 10., 11.],
          [12., 13., 14., 15., 16., 17.],
          [18., 19., 20., 21., 22., 23.],
          [24., 25., 26., 27., 28., 29.],
          [30., 31., 32., 33., 34., 35.]]]])

Output Tensor Shape: torch.Size([1, 1, 3, 3])
Output Tensor (Max Values) tensor([[[[ 7.,  9., 11.],
          [19., 21., 23.],
          [31., 33., 35.]]]])
Indices of Max Values:
 tensor([[[[ 7,  9, 11],
          [19, 21, 23],
          [31, 33, 35]]]])


In [9]:
#adaptive_max_pool3d 
# function applies 3d adaptive max pooling, 
# dynamically adjust the size of the pooling windows to produce a fixed output size. 
# it particularly useful when yo need a specific output size regardless the input size 

import torch 
import torch.nn.functional as F 

input_tensor = torch.arange(64,dtype=torch.float32).reshape(1,1,4,4,4)
print('Input Tensor Shape:', input_tensor.shape)
print('Input Tensor:\n', input_tensor)

output_size = (2,2,2)
return_indices = True 

output, indices = F.adaptive_max_pool3d(
    input = input_tensor,
    output_size = output_size,
    return_indices = return_indices 
)
print('\n Output Tensor Shape:', output.shape)
print('Output Tensor (Max Values):\n', output)
print('Indices of Max Values:\n', indices)

Input Tensor Shape: torch.Size([1, 1, 4, 4, 4])
Input Tensor:
 tensor([[[[[ 0.,  1.,  2.,  3.],
           [ 4.,  5.,  6.,  7.],
           [ 8.,  9., 10., 11.],
           [12., 13., 14., 15.]],

          [[16., 17., 18., 19.],
           [20., 21., 22., 23.],
           [24., 25., 26., 27.],
           [28., 29., 30., 31.]],

          [[32., 33., 34., 35.],
           [36., 37., 38., 39.],
           [40., 41., 42., 43.],
           [44., 45., 46., 47.]],

          [[48., 49., 50., 51.],
           [52., 53., 54., 55.],
           [56., 57., 58., 59.],
           [60., 61., 62., 63.]]]]])

 Output Tensor Shape: torch.Size([1, 1, 2, 2, 2])
Output Tensor (Max Values):
 tensor([[[[[21., 23.],
           [29., 31.]],

          [[53., 55.],
           [61., 63.]]]]])
Indices of Max Values:
 tensor([[[[[21, 23],
           [29, 31]],

          [[53, 55],
           [61, 63]]]]])


In [10]:
#adapative_avg_pool2d

#function applies 2d adaptive average pooling, dynamically adjust the size of the pooling windows to produce fixed outut size.
# it sizes it computes the average value wihtint each region mkaing it useful for downsampling while spatiol 

import torch 
import torch.nn.functional as F 

input_tensor = torch.arange(36, dtype=torch.float32).reshape(1,1,6,6)
print('Input Tensor Shape:', input_tensor.shape)
print('Input Tensor:\n', input_tensor)

output_size = (3,3)

output = F.adaptive_avg_pool2d(
    input = input_tensor,
    output_size=output_size
)

print('\nOutput Tensor Shape:', output.shape)
print('Output')

Input Tensor Shape: torch.Size([1, 1, 6, 6])
Input Tensor:
 tensor([[[[ 0.,  1.,  2.,  3.,  4.,  5.],
          [ 6.,  7.,  8.,  9., 10., 11.],
          [12., 13., 14., 15., 16., 17.],
          [18., 19., 20., 21., 22., 23.],
          [24., 25., 26., 27., 28., 29.],
          [30., 31., 32., 33., 34., 35.]]]])

Output Tensor Shape: torch.Size([1, 1, 3, 3])
Output


In [11]:
# adaptive_avg_pool3d 

# function applies 3d adaptive average pooling, which dynmically adjusts the size of the poooling windows to produce a dixed output size. 
# it computes the average value within each region , making it useful for downsampling volunteric data while preserving spatioal information.

import torch 
import torch.nn.functional as F 

input_tensor = torch.arange(64, dtype=torch.float32).reshape(1,1,4,4,4)
print('Input Tensor Shape', input_tensor.shape)
print('Input Tensor:', input_tensor)

output_size = (2,2,2)

output = F.adaptive_avg_pool3d(
    input = input_tensor,
    output_size=output_size
)

print('\n Output Tensor Shape:', output.shape)
print('\n Output Tensor (Average Values):', output)

Input Tensor Shape torch.Size([1, 1, 4, 4, 4])
Input Tensor: tensor([[[[[ 0.,  1.,  2.,  3.],
           [ 4.,  5.,  6.,  7.],
           [ 8.,  9., 10., 11.],
           [12., 13., 14., 15.]],

          [[16., 17., 18., 19.],
           [20., 21., 22., 23.],
           [24., 25., 26., 27.],
           [28., 29., 30., 31.]],

          [[32., 33., 34., 35.],
           [36., 37., 38., 39.],
           [40., 41., 42., 43.],
           [44., 45., 46., 47.]],

          [[48., 49., 50., 51.],
           [52., 53., 54., 55.],
           [56., 57., 58., 59.],
           [60., 61., 62., 63.]]]]])

 Output Tensor Shape: torch.Size([1, 1, 2, 2, 2])

 Output Tensor (Average Values): tensor([[[[[10.5000, 12.5000],
           [18.5000, 20.5000]],

          [[42.5000, 44.5000],
           [50.5000, 52.5000]]]]])


In [12]:
#max_pool2d 

# function applies 2d fractional max pooling whcih downsamples the input by selecting a random subset of pooling regions 

import torch 
import torch.nn.functional as F 

input_tensor = torch.arange(64, dtype=torch.float32).reshape(1,1,8,8)
print('Input Tensor Shape:', input_tensor.shape)
print('Input Tensor', input_tensor)

kernel_size = 3 
output_size = (4,4)
return_indices = True 

output , indices = F.fractional_max_pool2d(
    input = input_tensor,
    kernel_size = kernel_size, 
    output_size = output_size, 
    return_indices = return_indices
)

print('\nOutput Tensor Shape:', output.shape)
print('Output Tensor (Max Values):\n', output)
print('Indices of Max Values\n', indices)

Input Tensor Shape: torch.Size([1, 1, 8, 8])
Input Tensor tensor([[[[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11., 12., 13., 14., 15.],
          [16., 17., 18., 19., 20., 21., 22., 23.],
          [24., 25., 26., 27., 28., 29., 30., 31.],
          [32., 33., 34., 35., 36., 37., 38., 39.],
          [40., 41., 42., 43., 44., 45., 46., 47.],
          [48., 49., 50., 51., 52., 53., 54., 55.],
          [56., 57., 58., 59., 60., 61., 62., 63.]]]])

Output Tensor Shape: torch.Size([1, 1, 4, 4])
Output Tensor (Max Values):
 tensor([[[[18., 19., 21., 23.],
          [34., 35., 37., 39.],
          [42., 43., 45., 47.],
          [58., 59., 61., 63.]]]])
Indices of Max Values
 tensor([[[[18, 19, 21, 23],
          [34, 35, 37, 39],
          [42, 43, 45, 47],
          [58, 59, 61, 63]]]])


In [13]:
#max_pool3d

import torch 
import torch.nn.functional as F 

input_tensor = torch.arange(512, dtype=torch.float32).reshape(1,1,8,8,8)
print('Input Tensor Shape:', input_tensor.shape)
print('Input Tensor:\n', input_tensor)

kernel_size = 3
output_size = (4,4,4)
return_indices = True 

output, indices = F.fractional_max_pool3d(
    input = input_tensor,
    kernel_size = kernel_size,
    output_size = output_size,
    return_indices = return_indices 
)

print('\n Output Tensor Shape:', output.shape)
print('Output Tensor (Max Values)\n', output)
print('Indices of Max Values:\n',indices)

Input Tensor Shape: torch.Size([1, 1, 8, 8, 8])
Input Tensor:
 tensor([[[[[  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.],
           [  8.,   9.,  10.,  11.,  12.,  13.,  14.,  15.],
           [ 16.,  17.,  18.,  19.,  20.,  21.,  22.,  23.],
           [ 24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.],
           [ 32.,  33.,  34.,  35.,  36.,  37.,  38.,  39.],
           [ 40.,  41.,  42.,  43.,  44.,  45.,  46.,  47.],
           [ 48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.],
           [ 56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.]],

          [[ 64.,  65.,  66.,  67.,  68.,  69.,  70.,  71.],
           [ 72.,  73.,  74.,  75.,  76.,  77.,  78.,  79.],
           [ 80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.],
           [ 88.,  89.,  90.,  91.,  92.,  93.,  94.,  95.],
           [ 96.,  97.,  98.,  99., 100., 101., 102., 103.],
           [104., 105., 106., 107., 108., 109., 110., 111.],
           [112., 113., 114., 115., 116., 117., 118., 119.],
           [120., 12

In [18]:
#scaled_dot_product_attention

# computes scaled dot-product attention 
# which core operation transformer-based models 
# it supports features like attention masking, dropout and causal attension.
import torch
import torch.nn.functional as F

# Define query, key, and value tensors
batch_size = 2
num_heads = 4
seq_len_query = 8
seq_len_key_value = 10
embedding_dim = 64

query = torch.rand(batch_size, num_heads, seq_len_query, embedding_dim)  # Shape: (N, Hq, L, E)
key = torch.rand(batch_size, num_heads, seq_len_key_value, embedding_dim)  # Shape: (N, H, S, E)
value = torch.rand(batch_size, num_heads, seq_len_key_value, embedding_dim)  # Shape: (N, H, S, Ev)

# Optional attention mask (float mask that adds bias to attention scores)
attn_mask = torch.tril(torch.ones(seq_len_query, seq_len_key_value))  # Lower triangular mask
attn_mask = attn_mask.masked_fill(attn_mask == 0, float("-inf")).masked_fill(attn_mask == 1, 0.0)

# Parameters for scaled_dot_product_attention
dropout_p = 0.1  # Dropout probability
is_causal = False  # Whether to apply causal masking
scale = None  # Scaling factor (default is 1 / sqrt(embedding_dim))
enable_gqa = False  # Enable Grouped Query Attention (experimental)

# Apply scaled dot-product attention
attention_output = F.scaled_dot_product_attention(
    query=query,
    key=key,
    value=value,
    attn_mask=attn_mask,
    dropout_p=dropout_p,
    is_causal=is_causal,
    scale=scale,
    enable_gqa=enable_gqa
)

# Print the output tensor
print("Attention Output Shape:", attention_output.shape)
print("Attention Output:\n", attention_output)


Attention Output Shape: torch.Size([2, 4, 8, 64])
Attention Output:
 tensor([[[[0.2649, 0.4282, 0.9530,  ..., 0.6633, 0.2831, 0.6720],
          [0.6438, 0.5081, 0.8578,  ..., 0.7205, 0.1772, 0.8333],
          [0.4574, 0.6657, 0.6882,  ..., 0.7768, 0.4474, 0.9025],
          ...,
          [0.5056, 0.4177, 0.4656,  ..., 0.5272, 0.3969, 0.6563],
          [0.7042, 0.5366, 0.5024,  ..., 0.4751, 0.5923, 0.7479],
          [0.6596, 0.5777, 0.4738,  ..., 0.5001, 0.5570, 0.6923]],

         [[1.0778, 0.5960, 0.7437,  ..., 0.3600, 0.9837, 0.7020],
          [0.2299, 0.4553, 0.0534,  ..., 0.1464, 0.0436, 0.2850],
          [0.5496, 0.5532, 0.4163,  ..., 0.3606, 0.6794, 0.5596],
          ...,
          [0.2894, 0.4028, 0.4763,  ..., 0.4075, 0.4890, 0.4804],
          [0.4760, 0.3388, 0.4006,  ..., 0.3396, 0.4056, 0.4513],
          [0.5099, 0.3814, 0.4191,  ..., 0.4421, 0.4335, 0.4065]],

         [[0.6909, 0.0219, 0.7772,  ..., 0.5716, 0.5740, 1.0567],
          [0.7070, 0.0311, 0.3964,  ...

In [19]:
#threshold 

import torch 
import torch.nn.functional as F 

input_tensor = torch.tensor([[-1.0 , 2.0, -3.0], [4.0, -5.0, 6.0]])
print('Input Tensor:\n', input_tensor)

threshold = 0.0 
value = 0.0 
inplace = False 

output_tensor = F.threshold(input = input_tensor, threshold=threshold, value =value, inplace=inplace)

print('\nOutput Tensor:\n',output_tensor)

Input Tensor:
 tensor([[-1.,  2., -3.],
        [ 4., -5.,  6.]])

Output Tensor:
 tensor([[0., 2., 0.],
        [4., 0., 6.]])


In [20]:


import torch 
import torch.nn.functional as F 

input_tensor = torch.tensor([[-1.0, 2.0, -3.0],[4.0, -5.0, 6.0]])
print('Original Input Tensor:\n', input_tensor)

threshold = 0.0
value = 0.0 

F.threshold_(input=input_tensor, threshold=threshold, value=value)

print('\n Modified Input Tensor (In-Place):\n', input_tensor)




Original Input Tensor:
 tensor([[-1.,  2., -3.],
        [ 4., -5.,  6.]])

 Modified Input Tensor (In-Place):
 tensor([[0., 2., 0.],
        [4., 0., 6.]])


In [21]:
#relu 

# this function applies the rectified linear unit (ReLU)

import torch 
import torch.nn.functional as F 

input_tensor = torch.tensor([[-1.0, 2.0, -3.0],[4.0, -5.0, 6.0]])
print('Input Tensor:\n', input_tensor)

output_tensor = F.relu(input=input_tensor, inplace = False)
print('\nOutput Tensor(ReLU):\n', output_tensor)

Input Tensor:
 tensor([[-1.,  2., -3.],
        [ 4., -5.,  6.]])

Output Tensor(ReLU):
 tensor([[0., 2., 0.],
        [4., 0., 6.]])


In [23]:
#relu_

import torch 
import torch.nn.functional as F 
input_tensor = torch.tensor([[-1.0, 2.0, -3.0],[4.0, -5.0, 6.0]])
print('Original Input Tensor:\n', input_tensor)
F.relu_(input=input_tensor)
print('\nModified Input Tensor (ReLU In-Place):\n', input_tensor)

Original Input Tensor:
 tensor([[-1.,  2., -3.],
        [ 4., -5.,  6.]])

Modified Input Tensor (ReLU In-Place):
 tensor([[0., 2., 0.],
        [4., 0., 6.]])


In [3]:
#hardtanh
# applies hardtanh function element-wise
# hardtanh is an activation function used for neural networks, it is cheaper and more computatinally efficient version of the tanh activation
# hardtanh function clamps all values in the tensor to a specified range [min_val, max_val] 
# value beelow min_val are set to min_val and values above max-val are set to max_val

import torch 
import torch.nn.functional as F 

input_tensor = torch.tensor([[-2.0,-0.5,0.0],[0.5,1.5,3.0]])
print('Input Tensor:\n', input_tensor)

min_val = -1.0 
max_val = 1.0
inplace = False 

output_tensor = F.hardtanh(input=input_tensor, min_val=min_val,max_val=max_val,inplace=inplace)

print('\nOutput Tensor (HardTanh):\n', output_tensor)


##value clamping
#clamping values to a specific range is useful in scenarios where you want to restrict the output or intermediate results of computations to a predefined range
# help prevent numerical instability or ensure that outputs meet certain constraints

#simulated activations from a layer
activations = torch.tensor([[-5.0,-2.0,0.0],[1.0,3.0,10.0]])

#clamp activations to the range
clamped_activations = F.hardtanh(activations, min_val=-1.0, max_val=1.0)
print('Oirignal Activations:\n', activations)
print('\nClamped Activations:\n', clamped_activations)

#Gradient Stability
# gradients can someines explode (becomde very large) or vanis become very small.applying a clapming operation like hartanh can help stabilize gradeints by restricint their magnitde.


gradients = torch.tensor([[-10.0, -5.0, 0.0],[-1.0, 5.0, 20.0]])

clipped_gradients = torch.clamp(gradients, min=-1.0, max=1.0)

print('Original Gradietns:\n',gradients)
print('\nClupped Gradients:\n',clipped_gradients)

#in-place hardtanh
activations = torch.tensor([[-5.0, -2.0, 0.0],[1.0, 3.0, 10.0]])

print('Original Activations:\n', activations)
F.hardtanh_(activations, min_val=-1.0, max_val=1.0)
print('\nModified Activations (In-Place):\n',activations)

"""
Value Clamping Restricts values to a specific range
Gradient Stability Limits gradients to a safe range to prevent exploding or vanishing gradients
In-Place HardTanh Modifies the input tensor directly to save memory
"""

Input Tensor:
 tensor([[-2.0000, -0.5000,  0.0000],
        [ 0.5000,  1.5000,  3.0000]])

Output Tensor (HardTanh):
 tensor([[-1.0000, -0.5000,  0.0000],
        [ 0.5000,  1.0000,  1.0000]])
Oirignal Activations:
 tensor([[-5., -2.,  0.],
        [ 1.,  3., 10.]])

Clamped Activations:
 tensor([[-1., -1.,  0.],
        [ 1.,  1.,  1.]])
Original Gradietns:
 tensor([[-10.,  -5.,   0.],
        [ -1.,   5.,  20.]])

Clupped Gradients:
 tensor([[-1., -1.,  0.],
        [-1.,  1.,  1.]])
Original Activations:
 tensor([[-5., -2.,  0.],
        [ 1.,  3., 10.]])

Modified Activations (In-Place):
 tensor([[-1., -1.,  0.],
        [ 1.,  1.,  1.]])


'\nValue Clamping Restricts values to a specific range\nGradient Stability Limits gradients to a safe range to prevent exploding or vanishing gradients\nIn-Place HardTanh Modifies the input tensor directly to save memory\n'

In [4]:
#hardswish , applies hardswish activation function element-wise to the input tensor.
# hwardswish is a computationally efficient approximation of the swish activation function
# coonly used in lightweight nuerak netrks like mobilenetv3

import torch 
import torch.nn.functional as F 

input_tensor = torch.tensor([[-4.0, -2.0, 0.0],[1.0,3.0,5.0]])

print('input tensor:\n', input_tensor)

output_tensor = F.hardswish(input=input_tensor, inplace=False)
print('\nOutput Tensor (HardSwish):\n',output_tensor)



input tensor:
 tensor([[-4., -2.,  0.],
        [ 1.,  3.,  5.]])

Output Tensor (HardSwish):
 tensor([[-0.0000, -0.3333,  0.0000],
        [ 0.6667,  3.0000,  5.0000]])


In [9]:
#here are hardswihc with MobileNetV3Block


import torch 
import torch.nn as nn 
import torch.nn.functional as F 

class MobileNetV3Block(nn.Module):
    def __init__(self, in_channels, out_channels, expansion_factor=6, kernel_size=3, stride=1):
        super(MobileNetV3Block, self).__init__()

        #expandions phase
        hidden_dim = int(in_channels * expansion_factor)
        self.use_residual = (stride == 1 and in_channels == out_channels)

        layers = []

        if expansion_factor != 1:
            layers.append(nn.Conv2d(in_channels, hidden_dim,kernel_size=1,bias=False))
            layers.append(nn.BatchNorm2d(hidden_dim))
            layers.append(nn.Hardswish())

        layers.append(nn.Conv2d(hidden_dim, hidden_dim, kernel_size=1, bias =False ))
        layers.append(nn.BatchNorm2d(hidden_dim))
        layers.append(nn.Hardswish())

        #pointwise convolution (projection)
        layers.append(nn.Conv2d(hidden_dim, out_channels,kernel_size=1, bias =False))
        layers.append(nn.BatchNorm2d(out_channels))

        self.conv = nn.Sequential(*layers)
    def forward(self,x):
        if self.use_residual:
            return x + self.conv(x)
        else:
            return self.conv(x)

input_tensor = torch.randn(1,16,32,32)
mobilenet_block = MobileNetV3Block(in_channels=16, out_channels=16, expansion_factor=6, kernel_size=3, stride=1)
output_tensor = mobilenet_block(input_tensor)
print('Output Tensor Shape:', output_tensor.shape)


# MobileNetV3 Block Structure :
# The block follows the structure of a typical MobileNetV3 bottleneck block:
# Expansion Phase : A pointwise convolution increases the number of channels by a factor (expansion_factor), followed by BatchNorm and HardSwish activation.
# Depthwise Convolution : A depthwise convolution applies spatial filtering, followed by BatchNorm and HardSwish activation.
# Projection Phase : Another pointwise convolution reduces the number of channels back to out_channels, followed by BatchNorm.
# HardSwish Activation :
# HardSwish is applied after both the expansion and depthwise convolution phases to introduce non-linearity efficiently.
# Residual Connection :
# If the input and output dimensions match (in_channels == out_channels and stride == 1), a residual connection is added to improve gradient flow.
# Input Tensor :
# A dummy input tensor of shape (1, 16, 32, 32) is passed through the block.
# Output Tensor :
# The output tensor has the same shape as the input tensor due to the residual connection.

Output Tensor Shape: torch.Size([1, 16, 32, 32])


In [1]:
#relu6 activattion function element-wise to the input tensor.
#relu6 clamps all values in the tensor to the range [0,6] specifically
# * values less than 0 and are set to 0 
# * values greater than 6 are set to 6
# values within range [0,6] remained unchanged

import torch 
import torch.nn.functional as F

input_tensor = torch.tensor([[-2.0,3.0,8.0],[5.0,-1.0,6.0]])
print('Input Tensor:\n',input_tensor)

#apply relu6 
output_tensor = F.relu6(input=input_tensor, inplace=False)
print('\nOutput Tensor (Relu6):\n', output_tensor)

Input Tensor:
 tensor([[-2.,  3.,  8.],
        [ 5., -1.,  6.]])

Output Tensor (Relu6):
 tensor([[0., 3., 6.],
        [5., 0., 6.]])


In [3]:
#elu 
# applies exponential linear unit (elu) 
# elu activation function element-wise to the input tensor

import torch 
import torch.nn.functional as F 

input_tensor = torch.tensor([[-2.0, -1.0, 0.0], [1.0, 2.0, 3.0]])
print('input tensor:\n', input_tensor)

alpha = 1.0
inplace = False 

output_tensor = F.elu(input=input_tensor, alpha=alpha, inplace=inplace)

print('\nOutput Tensur (ELU):\n',output_tensor)

# F.elu_(input=input_tensor, alpha=alpha) #apply elu activation in-place


input tensor:
 tensor([[-2., -1.,  0.],
        [ 1.,  2.,  3.]])

Output Tensur (ELU):
 tensor([[-0.8647, -0.6321,  0.0000],
        [ 1.0000,  2.0000,  3.0000]])


In [4]:
#selu

# this function applies the Scaled Explonential Linear Unit (SELU) activation function element-wise to the input tensor.
# SLUE is a self normalizing activation function that helps maintain mean and variance stability during training, making it particularly useful in deep nueral networks


import torch 
import torch.nn.functional as F 

input_tensor = torch.tensor([[-2.0, -1.0, 0.0], [1.0, 2.0, 3.0]])
print('input tensor:\n', input_tensor)

inplace = False

output_tensor = F.selu(input=input_tensor, inplace=inplace)
print('output tensor (selu):\n', output_tensor)

input tensor:
 tensor([[-2., -1.,  0.],
        [ 1.,  2.,  3.]])
output tensor (selu):
 tensor([[-1.5202, -1.1113,  0.0000],
        [ 1.0507,  2.1014,  3.1521]])


In [5]:
#celu 
# this function applies the continously differentiable exponential linear unit (celu) activation function element-wise to the input tensor.
import torch 
import torch.nn.functional as F 
input_tensor = torch.tensor([[-2.0, -1.0, 0.0], [1.0, 2.0, 3.0]])
print('input tensor:\n', input_tensor)

alpha = 1.0
inplace = False 

output_tensor = F.celu(input= input_tensor, alpha=alpha, inplace=inplace)
print('\noutput tensor (celu):\n', output_tensor)

input tensor:
 tensor([[-2., -1.,  0.],
        [ 1.,  2.,  3.]])

output tensor (celu):
 tensor([[-0.8647, -0.6321,  0.0000],
        [ 1.0000,  2.0000,  3.0000]])


In [9]:
#leaky-relu
# function applies the leaky rectified linear unit activation function element-wise to the input tensor
# leaky relu is a variant of relu that allows a small, non-zero gradient for negetive inputs, controlled by the negative_slope parameter


import torch
import torch.nn.functional as F 

input_tensor = torch.tensor([[-2.0, -1.0, 0.0],[1.0, 2.0, 3.0]])
print('input tensor:\n',input_tensor)

negative_slope = 0.01 
inplace = False 

output_tensor = F.leaky_relu(input=input_tensor, negative_slope=negative_slope, inplace=inplace)

print('output tensor (leaky ReLU):\n',output_tensor)

input tensor:
 tensor([[-2., -1.,  0.],
        [ 1.,  2.,  3.]])
output tensor (leaky ReLU):
 tensor([[-0.0200, -0.0100,  0.0000],
        [ 1.0000,  2.0000,  3.0000]])


In [10]:
#parametric rectified linear unit (PReLU)
# activation function element-wise to the input tensor.
# unlike leaky relu, PReLUL allows the slope for negative inputs (weight) to be a learnable parameter which can adapt during training 

import torch 
import torch.nn.functional as F 

input_tensor = torch.tensor([[-2.0,-1.0,0.0],[1.0,2.0,3.0]])
print('input tensor:\n', input_tensor)

#define the learnable weight parameter for PReLU
#weight can be a scaler or a 1-D tensor matching the number of input chanels
weight = torch.tensor(0.25)
output_tensor = F.prelu(input=input_tensor, weight=weight)

#print the output tensor
print('\nOuput Tensor (PReLU)\n', output_tensor)


input tensor:
 tensor([[-2., -1.,  0.],
        [ 1.,  2.,  3.]])

Ouput Tensor (PReLU)
 tensor([[-0.5000, -0.2500,  0.0000],
        [ 1.0000,  2.0000,  3.0000]])


In [12]:
#rrelu
# randomized leaky rectified linear unit (rrelu) activtaion function element-wise to the input tensor
# RReLU introduces randomness in the slope for negative inputs during training , which can help with generalization
# a is a randmly sampled from a unifrom distribution [lower, upper] during training, during inference a is fixed o the average of [lower, upper]

import torch 
import torch.nn.functional as F 

input_tensor = torch.tensor([[-2.0,-2.0,0.0],[1.0,2.0,3.0]])
print('input tensor\n',input_tensor)

lower = 1./8
upper = 1./3
training = True 
inplace = False 

output_tensor = F.rrelu(input=input_tensor, lower=lower, upper=upper, training=training, inplace=inplace)
print('\noutput tensor (RReLU):\n', output_tensor)

input tensor
 tensor([[-2., -2.,  0.],
        [ 1.,  2.,  3.]])

output tensor (RReLU):
 tensor([[-0.6247, -0.3263,  0.0000],
        [ 1.0000,  2.0000,  3.0000]])


In [14]:
#glu (gated linear unit)
# splits the input tensor along a specified dimension into two parts (a and b) applies the sigmoid function to b and computs the lement-wisr product a and a(b)

import torch 
import torch.nn.functional as F 

input_tensor = torch.randn(2,8)
print('input tensor:\n', input_tensor)

dim = -1
output_tensor = F.glu(input=input_tensor, dim=dim)

print('\output tensor (glu):\n', output_tensor)

input tensor:
 tensor([[ 0.7922, -1.1832, -0.2774, -1.9988,  0.0403,  0.0956, -1.7005, -0.1549],
        [ 1.4411, -0.7484, -0.8632,  1.1396,  1.0872, -0.6204, -0.6409,  0.7428]])
\output tensor (glu):
 tensor([[ 0.4041, -0.6199, -0.0428, -0.9222],
        [ 1.0777, -0.2617, -0.2978,  0.7722]])


In [15]:
#gelu (gaussian error linear unit)
#activation function element-wise to the input tensor
# GELU is smooth non-linear activation function that is widely used in modern deep learning models

import torch
import torch.nn.functional as F 

input_tensor = torch.tensor([-2.0,-1.0,0.0,1.0,2.0])
print('input tensor:\n',input_tensor)

output_exact = F.gelu(input=input_tensor, approximate='none')
output_approximate = F.gelu(input=input_tensor, approximate='tanh')

print('output tensor (exact GELU):\n',output_exact)
print('\noutput tensor (approximate GELU):\n',output_approximate)

input tensor:
 tensor([-2., -1.,  0.,  1.,  2.])
output tensor (exact GELU):
 tensor([-0.0455, -0.1587,  0.0000,  0.8413,  1.9545])

output tensor (approximate GELU):
 tensor([-0.0454, -0.1588,  0.0000,  0.8412,  1.9546])
