In [4]:
## Containers

## Modules

import torch 
import torch.nn as nn
import torch.nn.functional as F

class Model(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1  =nn.Conv2d(1,20,5)
        self.conv2 = nn.Conv2d(20,20,5)

    def forward(self,x):
        x = F.relu(self.conv1(x))
        x = F.relu(self.conv1(x))
        return x
    
model = Model()

print(model)

dummy_input = torch.randn(1,1,28,28)

# output = model(dummy_input)

# print("Output shape:", output)

Model(
  (conv1): Conv2d(1, 20, kernel_size=(5, 5), stride=(1, 1))
  (conv2): Conv2d(20, 20, kernel_size=(5, 5), stride=(1, 1))
)


In [9]:
## add_module

import torch
import torch.nn as nn

class DynamicModel(nn.Module):
    def __init__(self,input_size,hidden_sizes,output_size):
        super().__init__()

        self.add_module('input_layer',nn.Linear(input_size,hidden_sizes[0]))

        #Hidden Layers
        for i, hidden_size in enumerate(hidden_sizes):
            if i > 0:
                layer_name = f'hidden_layer_{i}'
                self.add_module(layer_name, nn.Linear(hidden_sizes[i-1], hidden_size))

        #output layer
        self.add_module('output_layer',nn.Linear(hidden_sizes[-1], output_size))

    def forward(self,x):
        for name, module in self.named_children():
            x = torch.relu(module(x))
        return x
    

input_size = 10

hidden_sizes = [20,30,40]

output_sizes = 5

model = DynamicModel(input_size, hidden_sizes, output_sizes)
print(model)

DynamicModel(
  (input_layer): Linear(in_features=10, out_features=20, bias=True)
  (hidden_layer_1): Linear(in_features=20, out_features=30, bias=True)
  (hidden_layer_2): Linear(in_features=30, out_features=40, bias=True)
  (output_layer): Linear(in_features=40, out_features=5, bias=True)
)


In [11]:
# add_module, adding predefined modules

import torch 
import torch.nn as nn

class CustomModel(nn.Module):
    def __init__(self):
        
        super().__init__()

        self.add_module('conv1', nn.Conv2d(1,32,kernel_size=3, stride=1, padding=1))

        sequential_layers = nn.Sequential(
            nn.Linear(32 * 28 , 128),
            nn.ReLU(),
            nn.Linear(128,10)
        )

        self.add_module('fc_layers', sequential_layers)

    def forward(self, x):
        x = torch.relu(self.conv1(x)) #apply ReLU after convolution
        x = x.view(x.size(0),-1)        #flatter the tensor
        x = self.fc_layers(x)           # pass through the sequential layers

#example usage
model = CustomModel()
print(model)

#test the model with dummy input
dummy_input = torch.randn(1,1,28,28)
# output = model(dummy_input)
# print("Output shape",output.shape)

CustomModel(
  (conv1): Conv2d(1, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (fc_layers): Sequential(
    (0): Linear(in_features=896, out_features=128, bias=True)
    (1): ReLU()
    (2): Linear(in_features=128, out_features=10, bias=True)
  )
)


In [14]:
# apply(fn) Weight Initializatins

# use to initialize the weights of all layers in a neural network using a custom initialization function

import torch
import torch.nn as nn

#define a custom weight initialization function
def init_weights(m):
    if isinstance(m,nn.Linear): # check if the module is a LInear layer
        nn.init.xavier_uniform_(m.weight) #Xavier initializaiton for weights
        if m.bias is not None:
            nn.init.zeros_(m.bias) #zero-initializae biases

class FeedForwardNet(nn.Module):
    def __init__(self, input_size, hidden_sizes, output_size):
        super().__init__()
        self.input_layer = nn.Linear(input_size, hidden_sizes[0])
        self.hidden_layers = nn.ModuleList([
            nn.Linear(hidden_sizes[i],hidden_sizes[i + 1]) for i in range(len(hidden_sizes) - 1)
        ])
        self.output_layer = nn.Linear(hidden_sizes[-1],output_size)
    def forward(self,x):
        x = torch.relu(self.input_layers(x))
        for layer in self.hidden_layers:
            x = torch.relu(layer(x))
        return self.output_layer(x)
    
input_size = 10
hidden_sizes = [20,30,40]
output_size = 5
model = FeedForwardNet(input_size, hidden_sizes, output_size)

#apply the weight initialization function to all layers
model.apply(init_weights)

#print the initialized weights of the first layer 
print("Initialized weights of input_layer:")
print(model.input_layer.weight)



Initialized weights of input_layer:
Parameter containing:
tensor([[-0.3189, -0.1001,  0.0435, -0.0555, -0.2206,  0.3877,  0.2900, -0.4394,
         -0.0062,  0.2300],
        [-0.3620, -0.1434,  0.2258, -0.1466,  0.2818, -0.2664,  0.2420, -0.1008,
          0.3838,  0.3238],
        [-0.3508, -0.4227, -0.0360,  0.0292, -0.4013,  0.2699, -0.1715,  0.1462,
          0.0721,  0.4111],
        [ 0.0515,  0.2634, -0.2497,  0.3960, -0.1172, -0.2831,  0.0980,  0.0502,
         -0.0728, -0.2099],
        [-0.4028, -0.2895, -0.2639, -0.4414,  0.3371, -0.0018,  0.3418, -0.2585,
         -0.0889,  0.2634],
        [-0.0484,  0.2885,  0.3568,  0.1521,  0.0667,  0.3111, -0.3108,  0.1520,
          0.2754,  0.2477],
        [ 0.1167, -0.2664, -0.2696, -0.3815, -0.0566,  0.2637,  0.2939, -0.2938,
          0.2794,  0.3037],
        [ 0.4436,  0.2564,  0.2436, -0.3032, -0.0301,  0.3401, -0.1926, -0.1543,
          0.1444, -0.1874],
        [-0.2768,  0.1304, -0.4417, -0.2970, -0.2713, -0.1505,  0.3054

In [16]:
#apply(fn) Freezing Layers

# use to freeze specific layers (disable gradient computation) in a model

import torch 
import torch.nn as nn

def freeze_layers(m):
    if isinstance(m, nn.Linear): #Freeze only Linear layers
        for param in m.parameters():
            param.requires_grad = False


class SimpleModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1 = nn.Linear(10,20)
        self.fc2 = nn.Linear(20,30)
        self.fc3 = nn.Linear(30,5)

    def forward(self,x):
        x = torch.relu(self.fc1(x))
        x = torch.relu(self.fc2(x))
        return self.fc3(x)
    

#create the model
model = SimpleModel()

#apply the freeze function to all layers
model.apply(freeze_layers)

for name,param in model.named_parameters():
    print(f"{name}: requires_grad = {param.requires_grad}")

fc1.weight: requires_grad = False
fc1.bias: requires_grad = False
fc2.weight: requires_grad = False
fc2.bias: requires_grad = False
fc3.weight: requires_grad = False
fc3.bias: requires_grad = False


In [17]:
#apply(fn) Logging Layer Informations

#log each layer information in the model

#define a loggin function

def log_layers(m):
    print(f"Layers: {m.__class__.__name__}, Parameters: {sum(p.numel() for p in m.parameters())}")

class ConvNet(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = nn.Conv2d(1,32,kernel_size = 3, stride=1, padding = 1)
        self.conv2 = nn.Conv2d(1,32,kernel_size = 3, stride=1, padding = 1)
        self.fc1 = nn.Linear(64 * 7 * 7 , 128)
        self.fc2 = nn.Linear(128, 10)

    def forward(self,x):
        x = torch.relu(self.conv1(x))
        x = torch.max_pool2d(x,2)
        x = torch.relu(self.conv2(x))
        x = torch.max_pool2d(x,2)
        x = x.view(x.size(0) - 1)
        x = torch.relu(self.fc1(x))
        return self.fc2(x)

model = ConvNet()
model.apply(log_layers)


"""

"""

Layers: Conv2d, Parameters: 320
Layers: Conv2d, Parameters: 320
Layers: Linear, Parameters: 401536
Layers: Linear, Parameters: 1290
Layers: ConvNet, Parameters: 403466


ConvNet(
  (conv1): Conv2d(1, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (conv2): Conv2d(1, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (fc1): Linear(in_features=3136, out_features=128, bias=True)
  (fc2): Linear(in_features=128, out_features=10, bias=True)
)

In [20]:
#bloat16()

# to cast all floating-point parameters and buffer of a model to bfloat16 data type.mro

# this is particularly supports bfloat16 ,suc as moden CPUs or TPUs

import torch 

import torch.nn as nn

#define a simple neural network
class SimpleModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1 = nn.Linear(10,20)
        self.fc2 = nn.Linear(20,30)
        self.fc3 = nn.Linear(30,5)

    def forward(self,x):
        x = torch.relu(self.fc1(x))
        x = torch.relu(self.fc2(x))
        return self.fc3(x)
    
#create the model
model = SimpleModel()

#print the initial data types of the parameters
print('before bfloat16 conversion')
for name, param, in model.named_parameters():
    print(f"{name}:{param.dtype}")


#convert the model to bfloat16
model = model.bfloat16()

#print the data types after the conversion
print("\nAfter bfloat16 conversion:")
for name, param in model.named_parameters():
    print(f"{name}:{param.dtype}")

#test the model with dummy input in bfloat16
dummy_input = torch.rand(1,10,dtype=torch.bfloat16) #input in bfloat16
output = model(dummy_input)
print("\n Output shape", output.shape)
print("Output dtype:", output.dtype)


before bfloat16 conversion
fc1.weight:torch.float32
fc1.bias:torch.float32
fc2.weight:torch.float32
fc2.bias:torch.float32
fc3.weight:torch.float32
fc3.bias:torch.float32

After bfloat16 conversion:
fc1.weight:torch.bfloat16
fc1.bias:torch.bfloat16
fc2.weight:torch.bfloat16
fc2.bias:torch.bfloat16
fc3.weight:torch.bfloat16
fc3.bias:torch.bfloat16

 Output shape torch.Size([1, 5])
Output dtype: torch.bfloat16


In [22]:
#buffer(recursive = True)

# used to iterate over all buffers of a module (and optionally its submodules) . Buffers are tensors that are part fo the module but are not trainable parameters.
# Example include running statistics in BatchNorm layers or fixed embeddings

import torch 
import torch.nn as nn

#define a model with buffers
class MyModel(nn.Module):
    def __init__(self):
        super().__init__()

        #trainable parameters
        self.fc1 = nn.Linear(10,20)
        self.fc2 = nn.Linear(20,30)

        #registering buffers
        self.register_buffer("running mean", torch.zeros(20))
        self.register_buffer("fixed_embeddings", torch.randn(5,10))

        #submodule with its own buffer
        self.submodule = nn.BatchNorm1d(30)

    def forwar(self, x):
        x = torch.relu(self.fc1(x))
        x = torch.relu(self.fc2(x))
        return self.submodule(x)
    

model = MyModel()

print("all buffers (recurse = True):")
for buf in model.buffers(recurse = True):
    print(type(buf), buf.size())

#interate over only direct buffers (recurse = False)
for buf in model.buffers(recurse = False):
    print(type(buf),buf.size())

all buffers (recurse = True):
<class 'torch.Tensor'> torch.Size([20])
<class 'torch.Tensor'> torch.Size([5, 10])
<class 'torch.Tensor'> torch.Size([30])
<class 'torch.Tensor'> torch.Size([30])
<class 'torch.Tensor'> torch.Size([])
<class 'torch.Tensor'> torch.Size([20])
<class 'torch.Tensor'> torch.Size([5, 10])


In [26]:
# compile() 

# powerful feature introduced to optimize the execution of models by leveraging advanced compiler techniques
# compiles forward method of a torch.nn.Module using torch.compile() which can significantly imporve performance by optmizing the model computation graph

import torch
import torch.nn as nn

class SimpleModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1 = nn.Linear(10,20)
        self.fc2 = nn.Linear(20,30)
        self.fc3 = nn.Linear(30,5)

    def forward(self,x):
        x = torch.relu(self.fc1(x))
        x = torch.relu(self.fc2(x))
        return self.fc3(x)

#create model and move it to the appropriate device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = SimpleModel().to(device)

#compile the model
compiled_model = torch.compile(model) #equivalent to calling model.compile

dummy_input = torch.randn(16,10,device = device)

output = compiled_model(dummy_input)

print("Output shape:", output.shape)

Output shape: torch.Size([16, 5])


In [27]:
# compile() Customization of compile

compiled_model = torch.compile(
    model,
    backend = "inductor",
    fullgraph=True,
    dynamic=False
)

output = compiled_model(dummy_input)
print("Output shape:", output.shape)

Output shape: torch.Size([16, 5])


In [28]:
#cuda(device = None)

#used to move al model parameters and buffer to a GPU for a sepcifc GPU if multiple are avaiable.
# important when you want to leverage GPU accelration for trainng or inference

import torch 
import torch.nn as nn 

#define a simple neural network
class SimpleMethod(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1 = nn.Linear(10,20)
        self.fc2 = nn.Linear(20,30)
        self.fc3 = nn.Linear(30,5)

    def forward(self,x):
        x = torch.relu(self.fc1(x))
        x = torch.relu(self.fc2(x))
        return self.fc3(x)
    
model = SimpleModel()

#check the initial device of the model's parameters
print("Initial device of parameters")

for name , param in model.named_parameters():
    print(f"{name}:{param.device}")


device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = model.to(device)

#verify that the model's parameters are now on the GPU
print("\n Device of parameters after moving to GPU:")
#move the model to the GPU
for name, param in model.named_parameters():
    print(f"{name}:{param.device}")

#create dummy input data and move it to the same device
dummy_input = torch.rand(16,10).to(device)

output = model(dummy_input)
print("\n Output shape:", output.shape)
print("Output device", output.device)
    





Initial device of parameters
fc1.weight:cpu
fc1.bias:cpu
fc2.weight:cpu
fc2.bias:cpu
fc3.weight:cpu
fc3.bias:cpu

 Device of parameters after moving to GPU:
fc1.weight:cpu
fc1.bias:cpu
fc2.weight:cpu
fc2.bias:cpu
fc3.weight:cpu
fc3.bias:cpu

 Output shape: torch.Size([16, 5])
Output device cpu


In [30]:
#double cast all floating-point paramets and buffer of a model to the torch.float64 

import torch 
import torch.nn as nn 

class SimpleModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1 = nn.Linear(10,20)
        self.fc2 = nn.Linear(20,30)
        self.fc3 = nn.Linear(30,5)

    def forward(self,x):
        x = torch.relu(self.fc1(x))
        x = torch.relu(self.fc2(x))
        return self.fc3(x)
    
model = SimpleModel()

print("Before double conversation")
for name, param in model.named_parameters():
    print(f"{name}: {param.dtype}")

#convert the model to double precision
model = model.double()

print("\n After double conversation:")
for name, param in model.named_parameters():
    print(f"{name}:{param.dtype}")

#test the model with dummy input in double precision
dummy_input = torch.randn(1,10, dtype=torch.float64) #input in double precision
output = model(dummy_input)

print("\n OUtput shape:", output.shape)
print("Output dtype:", output.dtype)

Before double conversation
fc1.weight: torch.float32
fc1.bias: torch.float32
fc2.weight: torch.float32
fc2.bias: torch.float32
fc3.weight: torch.float32
fc3.bias: torch.float32

 After double conversation:
fc1.weight:torch.float64
fc1.bias:torch.float64
fc2.weight:torch.float64
fc2.bias:torch.float64
fc3.weight:torch.float64
fc3.bias:torch.float64

 OUtput shape: torch.Size([1, 5])
Output dtype: torch.float64


In [33]:
#eval()

# used to set model into evaluatio mode. important for certain layers or modules that behave diferently during raining and evaliatons
# for example dropout, randomly drops units during raining but does not drop any units during evaluation
# also batchnorm uses running statistics (mean and variance) during evaluation instead of batch statistics

import torch 
import torch.nn as nn

#define a model with dropout and batchnorm layers
class MyModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1 = nn.Linear(10,20)
        self.dropout = nn.Dropout(p = 0.5)
        self.bn = nn.BatchNorm1d(20)
        self.fc2 = nn.Linear(20,5)

    def forward(self,x):
        x = torch.relu(self.fc1(x))
        x = self.dropout(x)
        x = self.bn(x)
        return self.fc2(x)
    
model = MyModel()

model.train()
print("Model in training mode:")
print(model)

#perform a forward pass with training mode
dummy_input = torch.randn(4,10)
output_train = model(dummy_input)
print("\n Outout in training mode:", output_train)

#set the model to evaluation mode
model.eval()
print("\n Model in evaluation mode:")
print(model)

#perform a forward pass with evaluatin mode
with torch.no_grad():
    output_eval = model(dummy_input)
print("\n Output in evaluation mode:", output_eval)


Model in training mode:
MyModel(
  (fc1): Linear(in_features=10, out_features=20, bias=True)
  (dropout): Dropout(p=0.5, inplace=False)
  (bn): BatchNorm1d(20, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (fc2): Linear(in_features=20, out_features=5, bias=True)
)

 Outout in training mode: tensor([[-0.3455, -0.6189,  0.7044, -1.5280,  0.4210],
        [-0.9519, -0.2885,  0.3518,  1.1750,  0.5380],
        [-0.1468,  0.4640, -0.1338, -0.0340, -0.7176],
        [ 0.6771,  0.6091, -0.5829,  0.2539, -0.6382]],
       grad_fn=<AddmmBackward0>)

 Model in evaluation mode:
MyModel(
  (fc1): Linear(in_features=10, out_features=20, bias=True)
  (dropout): Dropout(p=0.5, inplace=False)
  (bn): BatchNorm1d(20, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (fc2): Linear(in_features=20, out_features=5, bias=True)
)

 Output in evaluation mode: tensor([[-0.1544,  0.3611, -0.0028, -0.3084, -0.1717],
        [-0.1890,  0.0386,  0.1557,  0.0462, -0.0052],
      

In [34]:
#extra_repr
#override extra_repr methdinclude information about buffer 

import torch 
import torch.nn as nn 

#define a model with buffer
class MyModel(nn.Module):
    def __init__(self):
        super().__init__()

        #trainable parameters
        self.fc1 = nn.Linear(10,20)
        self.fc2 = nn.Linear(20,30)

        #registering buffers
        self.register_buffer("running_mean", torch.zeros(20))
        self.register_buffer("fixed_embeddings", torch.randn(5,10))
        self.submodule = nn.BatchNorm1d(30)

    def forward(self,x):
        x = torch.relu(self.fc1(x))
        x = torch.relu(self.fc2(x))
        return self.submodule(x)
    
    def extra_repr(self):
        return f"running mean: {self.running_mean.size()}, fixed_embeddings: {self.fixed_embeddings.size()}"

#instantiate the model
model = MyModel()
# print the model to see the extra represenation
print(model)
    
""""
this method is overriden to return a strin that provides additional information about the module,

it returns the sizes of the running_mean and fixed_embeddings buffers

"""

MyModel(
  running mean: torch.Size([20]), fixed_embeddings: torch.Size([5, 10])
  (fc1): Linear(in_features=10, out_features=20, bias=True)
  (fc2): Linear(in_features=20, out_features=30, bias=True)
  (submodule): BatchNorm1d(30, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
)


In [36]:
#float 

import torch 
import torch.nn as nn

#define a simpel model with paraemters and buffers

class MyModel(nn.Module):
    def __init__(self):
        super().__init__()
        #trainable parameter (default is float32)
        self.weight = nn.Parameter(torch.randn(3,3))

        #buffer (default is float32)
        self.register_buffer("running_mean", torch.zeros(3))

    def forward(self,x):
        return x @ self.weight + self.running_mean
    
model = MyModel()

#print the datatype of parameters and buffers before casting
print("Before float():")
print("Weight datatype:", model.weight.dtype)

print("Runnign mean datatype:", model.running_mean.dtype)

#cast all parameters and buffers to float (32-bit floating point)
model.float()

#print the datatype of parameters and buffers after casting
print("\n After float():")
print("Weight datatype:", model.weight.dtype)
print("Running mean datatype", model.running_mean.dtype)


model.double() #cast double precision
print("\n After float() again:")
print("Weight datatpye:", model.weight.dtype)
print("running mean datatype:", model.running_mean.dtype)

# casts all floating point parameter and buffer of the mode to the float datatpye torch.float32 

# dtyoe attrubte fo tensor indicates datatypes, by default pytorch uses toch.float32 

# float() double() is a in-place modification so no need to reassign the results.




Before float():
Weight datatype: torch.float32
Runnign mean datatype: torch.float32

 After float():
Weight datatype: torch.float32
Running mean datatype torch.float32

 After float() again:
Weight datatpye: torch.float64
running mean datatype: torch.float64


In [38]:
#forward 

#you should call model(x) directly instead of caling method.forward()
# this ensure that all any register hoooks (pre-forward , post-forward ) are executed. 

import torch
import torch.nn as nn

class MyModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1 = nn.Linear(10,20) #fully connected layer 1
        self.fc2 = nn.Linear(20,10) # fully connected layer 2
        self.relu = nn.ReLU() #activation function

    def forward(self,x):
        #define the foward pass
        x = self.fc1(x) #pass input throgu the first layer
        x = self.relu(x) #apply ReLU activation 
        x = self.fc2(x) #pass through the second layer 
        return x 
    
model = MyModel()

#craete a random input tensor
input_tensor = torch.randn(5,10)
# batch of 5 samples , each with 10 features

#perform forward pass by calling model
output = model(input_tensor)

print("input tensor shape", input_tensor.shape)
print("Output tensor shape:", output.shape)
print("Output tensor:\n", output)


input tensor shape torch.Size([5, 10])
Output tensor shape: torch.Size([5, 10])
Output tensor:
 tensor([[-0.3420,  0.0117,  0.1513, -0.1669,  0.2344, -0.3389, -0.1194, -0.0338,
         -0.0648,  0.0806],
        [-0.0349,  0.1871,  0.2086, -0.0350,  0.3173, -0.3457, -0.0485, -0.0875,
         -0.2528,  0.0297],
        [-0.1342,  0.1871,  0.2244, -0.2599,  0.1047, -0.1203, -0.0630, -0.2873,
          0.1868,  0.4255],
        [-0.0844,  0.2295,  0.1941, -0.0726,  0.1734, -0.4147, -0.2767, -0.2628,
         -0.1395,  0.1654],
        [-0.2090,  0.2179,  0.0762,  0.2524,  0.3752,  0.1334,  0.0876, -0.1751,
         -0.0287,  0.1636]], grad_fn=<AddmmBackward0>)


In [ ]:
#get_buffer(target)

# retrieve a specific buffer from a module using fully-qualified string name. 
# buffer are non-trainable tensors that are part of the module's state such as runnig statistics in BatchNorm

import torch 
import torch.nn as nn

class MyModel(nn.Module):
    def __init__(self):
        super().__init__()

        #register buffers
        self.register_buffer("running_mean", torch.zeros(10))

        self.register_buffer("fixed_embeddings", torch.randn(5,10))

        # add a submodule with its own buffer 
        self.submodule = nn.BatchNorm1d(10)
        self.submodule.register_buffer("running_var", torch.ones(10)) # buffer in submodule

    def forward(self,x):
        return self.submodule(x)
    
#instantiate the model
model = MyModel()

try:
    #get the  running_mean buffer from the main module
    running_mean = model.get_buffer("running_mean")
    print("Retrieved 'running_mean' buffer:")
    print(running_mean)

    #get the fixed_embeddigngs buffer fromt eh main module
    fixed_embeddings = model.get_buffer("fixed_embeddings")
    print("\nRetrieved 'fixed_embeddings' buffer:")
    print(fixed_embeddings)

    #get the running_var buffer from the submodule

    running_var = model.get_buffer("submodule.running_var")
    print("\nRetrieved 'submodule.running_var' buffer:")
    print(running_var)

    #attempt to get a non-existent buffer (will raiase error)
    non_existent_buffer = model.get_buffer("non_existent_buffer")

except AttributeError as e:
    print(f"\nError: {e}")


Retrieved 'running_mean' buffer:
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Retrieved 'fixed_embeddings' buffer:
tensor([[-0.0379, -0.1254, -0.2757, -0.8203,  2.3026, -0.7584, -0.7222, -0.3929,
          1.5857, -0.5442],
        [ 0.8620,  0.5481, -0.0808, -1.3729, -0.0415,  0.2268,  1.9648,  0.1972,
          0.1739, -0.7899],
        [-1.8245,  0.7981,  0.7574,  0.3576, -0.0595,  0.8876,  0.1681,  1.2019,
         -0.3573, -1.1934],
        [ 0.3252,  1.9988,  1.9587, -0.1001, -0.7791, -0.1302, -0.7127, -1.3451,
          0.0548,  0.5923],
        [ 0.4716,  1.1301,  0.8396, -0.0492,  0.6691,  1.9465, -0.1013,  0.0844,
         -1.1672, -1.7064]])

Retrieved 'submodule.running_var' buffer:
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Error: MyModel has no attribute `non_existent_buffer`


In [40]:
#get_extra_sate() 

#return any additional state that should be included in module's state_dict

import torch 
import torch.nn as nn 

class MyModel(nn.Module):
    def __init__(self):
        super().__init__()

        #trainable parameter
        self.weight = nn.Parameter(torch.randn(3,3))

        #extra state (non-tensor object)
        self.extra_state = {"description":"this is extra state","version": 1.0}

    def forward(self, x):
        return x @ self.weight 

    def get_extra_state(self):
        #return the extra state to be saved in the state_dict
        return self.extra_state
    
    def set_extra_state(self,state):
        self.extra_state = state 

model = MyModel()

# here we print the model's initial extra state
print("Initial extra state:", model.extra_state)

state_dict = model.state_dict()

#modify the extra state 
model.extra_state['version'] = 2.0 
print('\n Modified extra state:', model.extra_state)

#load the saved state_dict (restoring the original extra state)
model.load_state_dict(state_dict)

#print the restored extra state
print('\n Restored extra state:', model.extra_state)






Initial extra state: {'description': 'this is extra state', 'version': 1.0}

 Modified extra state: {'description': 'this is extra state', 'version': 2.0}

 Restored extra state: {'description': 'this is extra state', 'version': 2.0}


In [42]:
#get_parameter(target)

# retrieve specific parameter from a module using fully-qualified string name. 
# parameters are trainable tensors that are part of the module's state

import torch 
import torch.nn as nn 

class MyModel(nn.Module):
    def __init__(self):
        super().__init__()

        #define trainable parameters 
        self.weight = nn.Parameter(torch.randn(3,3)) #parameter 1
        self.bias = nn.Parameter(torch.zeros(3)) # parameter 2

        #add a subodule with its own parameter
        self.submodule = nn.Linear(3,3)

    def forward(self,x):
        return self.submodule(x @ self.weight + self.bias)
    
#instantiate the model
model = MyModel()

try:
    #get the weight parameter from the main module
    weight = model.get_parameter("weight")
    print("Retrieved 'weight parameter:")
    print(weight)

    #get the bias parameter from the main module 
    bias = model.get_parameter('bias')
    print('\n Retrieved bias parameter:')
    print(bias)

    #get tje 'weight' parameter from the submodule 
    submodule_weight = model.get_parameter('submodule.weight')
    print('\nRetrieved submodule.weight parameter:')
    print(submodule_weight)

    non_existent_param = model.get_parameter('non_existet_param')
except AttributeError as e:
    print(f'\nError: {e}')




Retrieved 'weight parameter:
Parameter containing:
tensor([[ 0.7960,  1.2377, -0.7411],
        [-0.1748, -2.5137, -0.2854],
        [ 0.8596,  0.8421, -0.4042]], requires_grad=True)

 Retrieved bias parameter:
Parameter containing:
tensor([0., 0., 0.], requires_grad=True)

Retrieved submodule.weight parameter:
Parameter containing:
tensor([[ 0.5092,  0.0822,  0.1512],
        [ 0.2763,  0.5701, -0.4478],
        [-0.2466, -0.5344, -0.0660]], requires_grad=True)

Error: MyModel has no attribute `non_existet_param`


In [ ]:

#get_submodule 

# used to retrieve a specific submodule from a module usign a fully-qualified string name

# useful when working with deeply nested modules , as it aalows to directly access a submodule wihtout iterating thorugh the entire module hierarchy
import torch 
import torch.nn as nn 

class MyModel(nn.Module):
    def __init__(self):
        super().__init__()

        self.net_b = nn.Sequential(
            nn.Conv2d(16, 33, kernel_size=(3, 3)),  # Submodule 1
            nn.ReLU(),                             # Submodule 2
            nn.MaxPool2d(kernel_size=(2, 2))       # Submodule 3
        )

        self.linear = nn.Linear(100,200)

    def forward(self,x):
        x = self.net_b(x)
        x = x.view(x.size(0), -1) #flatten the tensor
        x = self.liner(x)
        return x 
    
model = MyModel()

try:
    net_b = model.get_submodule('net_b')
    print('Retrieved net_b submodule:')
    print(net_b)

    linear = model.get_submodule('linear')
    print('\nRetrieved linear submodule')
    print(linear)

    #get the first layer of 'net_b' (conv2d)
    conv_layer = model.get_submodule('net_b.0')
    print('\n Retreived net_b.0 submodule (Conv2d):')
    print(conv_layer)

    non_existent_submodule = model.get_submodule("non_existent_submodule")

except AttributeError as e:
    print(f'\nError: {e}')


Retrieved net_b submodule:
Sequential(
  (0): Conv2d(16, 33, kernel_size=(3, 3), stride=(1, 1))
  (1): ReLU()
  (2): MaxPool2d(kernel_size=(2, 2), stride=(2, 2), padding=0, dilation=1, ceil_mode=False)
)

Retrieved linear submodule
Linear(in_features=100, out_features=200, bias=True)

 Retreived net_b.0 submodule (Conv2d):
Conv2d(16, 33, kernel_size=(3, 3), stride=(1, 1))

Error: MyModel has no attribute `non_existent_submodule`


In [47]:
#half()

#used to cast all floating-point parameters and buffers of a module to the half dataype
# particularly useful when working with models that need to use half-precision floating-point numbers such as when optimizing for memory usage or when

import torch 
import torch.nn as nn 

#define a simple model with parameters and buffers
class MyModel(nn.Module):
    def __init__(self):
        super().__init__()
        #trainable parameter (default is float32)
        self.weight = nn.Parameter(torch.randn(3,3))

        self.register_buffer('running_mean',torch.zeros(3))
    def forward(self,x):
        return x @ self.weight + self.running_mean
    
model = MyModel()

print('Before half():')
print('Weight datatype:', model.weight.dtype)
print('Running mean datatype', model.running_mean.dtype) #should be torch.float32

#cast all parameters and buffers to half (16-bit floating point)
model.half()

#print the datatpye of parameters and buffer after casting 
print('\n After half():')
print('Weight datatype:', model.weight.dtype)
print('Running mean datatype:', model.running_mean.dtype)

#example with double precision 64-bit floating point
model.double()
print('\nAfter double():')
print('Wegiht datatype:', model.weight.dtype)
print('Running mean datatype:', model.running_mean.dtype)

#cast back to half 16-bit floating point
model.half()
print('\n after half() again:')
print('weight datatype:', model.weight.dtype)
print('running mean datatype', model.running_mean.dtype)

Before half():
Weight datatype: torch.float32
Running mean datatype torch.float32

 After half():
Weight datatype: torch.float16
Running mean datatype: torch.float16

After double():
Wegiht datatype: torch.float64
Running mean datatype: torch.float64

 after half() again:
weight datatype: torch.float16
running mean datatype torch.float16


In [49]:
#ipu(device = None)

# method specific to Graphcore's IPU (intelligence processing unit) hardware
# used to move al model parameters and buffers ot the IPU device
# moving models to CPUs or GPUs , but specific for IPU hardware

import torch
import torch.nn as nn
import poptorch  # Graphcore's PopTorch library for IPU support

# Define a simple model
class MyModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1 = nn.Linear(10, 20)
        self.fc2 = nn.Linear(20, 10)

    def forward(self, x):
        x = torch.relu(self.fc1(x))
        x = self.fc2(x)
        return x

# Instantiate the model
model = MyModel()

# Print the device of model parameters before moving to IPU
print("Before moving to IPU:")
for name, param in model.named_parameters():
    print(f"{name} is on device: {param.device}")

# Move the model to IPU
model.ipu()  # Move all parameters and buffers to IPU

# Print the device of model parameters after moving to IPU
print("\nAfter moving to IPU:")
for name, param in model.named_parameters():
    print(f"{name} is on device: {param.device}")

# Optional: Specify a specific IPU device
model.ipu(device=1)  # Move to IPU device 1

# Print the device of model parameters after moving to a specific IPU device
print("\nAfter moving to IPU device 1:")
for name, param in model.named_parameters():
    print(f"{name} is on device: {param.device}")

ModuleNotFoundError: No module named 'poptorch'

In [50]:
#load_state_dict(state_dict, strict = True, assign =False)

#used to load the state of a model (parameters and buffers) from a dictionary state_dict

#commonly used to load pretrained model


import torch
import torch.nn as nn

# Define a simple model
class MyModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1 = nn.Linear(10, 20)
        self.fc2 = nn.Linear(20, 10)

    def forward(self, x):
        x = torch.relu(self.fc1(x))
        x = self.fc2(x)
        return x

# Instantiate the model
model = MyModel()

# Save the model's state_dict (simulating a checkpoint)
checkpoint = model.state_dict()

# Modify the model (e.g., add a new layer)
model.fc3 = nn.Linear(10, 5)

# Attempt to load the saved state_dict into the modified model
try:
    # Load with strict=True (default)
    model.load_state_dict(checkpoint, strict=True)
except RuntimeError as e:
    print(f"Error when strict=True: {e}")

# Load with strict=False (ignore missing or unexpected keys)
result = model.load_state_dict(checkpoint, strict=False)
print("\nLoading with strict=False:")
print("Missing keys:", result.missing_keys)  # Keys in the model but not in the checkpoint
print("Unexpected keys:", result.unexpected_keys)  # Keys in the checkpoint but not in the model

# Example with assign=True
# Create a new model and load the checkpoint with assign=True
new_model = MyModel()
new_model.load_state_dict(checkpoint, assign=True)

# Verify that the parameters are loaded correctly
print("\nParameters after loading with assign=True:")
for name, param in new_model.named_parameters():
    print(f"{name}: {param}")

Error when strict=True: Error(s) in loading state_dict for MyModel:
	Missing key(s) in state_dict: "fc3.weight", "fc3.bias". 

Loading with strict=False:
Missing keys: ['fc3.weight', 'fc3.bias']
Unexpected keys: []

Parameters after loading with assign=True:
fc1.weight: Parameter containing:
tensor([[ 9.3234e-02, -1.0406e-01,  2.0072e-01,  1.0068e-01, -2.6003e-01,
         -6.9717e-02, -1.3650e-01,  3.0242e-01, -5.5836e-02,  1.6532e-01],
        [ 2.0841e-01, -2.1912e-01,  1.9119e-01, -4.9851e-02,  5.7902e-02,
         -1.9379e-02,  2.4167e-01, -1.0543e-01, -1.3502e-01,  7.4048e-02],
        [-1.5762e-01, -2.3877e-01, -2.5111e-01,  2.1742e-01, -2.3223e-01,
         -2.0470e-01,  1.5878e-02, -9.4169e-02, -6.3247e-02, -5.5704e-02],
        [ 1.6315e-04, -1.3842e-01, -1.3518e-01, -7.3822e-02,  2.1311e-01,
          1.4191e-01,  4.4531e-02, -1.4384e-01, -1.2044e-01,  1.2828e-01],
        [-2.4574e-01, -2.9267e-01, -1.1814e-01, -2.8761e-01,  2.9364e-01,
          9.9065e-02,  3.1010e-01,  2

In [55]:
#modules() return an interator over all module sin the network, include top-level module and its submodule

#useful for inspecting or modifying all parts of a model. 

import torch 
import torch.nn as nn 

class MyModel(nn.Module):
    def __init__(self):
        
        super().__init__()
        #define layers 
        self.fc1 = nn.Linear(10,20)
        self.fc2 = nn.Linear(20,10)

        #define a sequantial submodule
        self.submodule = nn.Sequential(
            nn.Conv2d(1,16,kernel_size =3),
            nn.ReLU(),
            nn.MaxPool2d(kernel_size=2)
        )

    def forward(self,x):
        x = torch.relu(self.fc1(x))
        x = self.fc2(x)
        return x
    
model = MyModel()

#iterative over all modules in the network 
print('All modules in the network:')
for idx, module in enumerate(model.modules()):
    print(f"{idx} -> {module}")

#example with shared layers 
shared_layer = nn.Linear(2,2)
net = nn.Sequential(shared_layer, shared_layer)

print('\nModules in a network with a shared layers:')
for ifx , module in enumerate(net.modules()):
    print(f'{idx}->{module}')


All modules in the network:
0 -> MyModel(
  (fc1): Linear(in_features=10, out_features=20, bias=True)
  (fc2): Linear(in_features=20, out_features=10, bias=True)
  (submodule): Sequential(
    (0): Conv2d(1, 16, kernel_size=(3, 3), stride=(1, 1))
    (1): ReLU()
    (2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
)
1 -> Linear(in_features=10, out_features=20, bias=True)
2 -> Linear(in_features=20, out_features=10, bias=True)
3 -> Sequential(
  (0): Conv2d(1, 16, kernel_size=(3, 3), stride=(1, 1))
  (1): ReLU()
  (2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
)
4 -> Conv2d(1, 16, kernel_size=(3, 3), stride=(1, 1))
5 -> ReLU()
6 -> MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)

Modules in a network with a shared layers:
6->Sequential(
  (0): Linear(in_features=2, out_features=2, bias=True)
  (1): Linear(in_features=2, out_features=2, bias=True)
)
6->Linear(in_features=2, out_features=2, bias

In [ ]:
#tia(device = None)

# specific to Meta' MTIA (Meta Training and Inference Accelerator) hardware 

# used to move all model parameters and buffers to the MTIA device .index
# analogous to the `to(device)` method used for moving models to CPUs or GPUs but its tailored for MTIA hardware

# since MITA-speficic funtionality is not standard PyTorck library , and require Meta's epcilaized framework. so no code will be generated

In [56]:
# named_buffer(prefix ='', recurse = True, remove_duplicate = True)

# used to iterate oer all buffers in a module , yielding both the name of the buffer in a module , yileding both the name of the niffer and the bffer itself.

# buffers are non trainable tenosrs that are part of the module's state such as runnig statistics in BatchNorm layers or fixed embeddings 


import torch 
import torch.nn as nn

class Mymode(nn.Module):
    def __init__(self):
        super().__init__()
        self.register_buffer("running_mean", torch.zeros(10)) #buffer 1
        self.register_buffer('fixed_embeddings',torch.randn(5,10))  #buffer 2

        #add a submodule with it own buffer 
        self.submodule = nn.BatchNorm1d(10)
        self.submodule.register_buffer('running_var', torch.ones(10)) #bufer in submodule 

    def forward(self,x):
        return self.submodule()
    
model = MyModel()

#interate over all buffers in the model
print('All buffers in the model:')
for name, buf in model.named_buffers():
    print(f"{name}:{buf.size()}")

#iterate over only direct buffers (recurse = False)
print('\nDirect buffers in the model (recurse = False):')

for name, buf in model.named_buffers(recurse = False):
    print(f"{name}: {buf.size()}")

print('\n Accessing the running__var buffer in the submodule:')
for name , buf in model.named_buffers(recurse = False):
    print(f'{name}:{buf.size()}')

#iterate over buffers with a custom prefix 
print('\nBuffers iwth prefix model.')
for name, buf in model.named_buffers(prefix = 'model'):
    print(f'{name}:{buf.size()}')

#access a specific buffer by name 
print('\n Accessing the running_var buffer in the submodule')
for name, buf in model.named_buffers():
    if name == "submodule.running_var":
        print(f"{name}: {buf}")




All buffers in the model:

Direct buffers in the model (recurse = False):

 Accessing the running__var buffer in the submodule:

Buffers iwth prefix model.

 Accessing the running_var buffer in the submodule


In [ ]:
# named_children

https://chat.deepseek.com/a/chat/s/47c58dc4-c246-4404-b900-8cfadc9bbee8

https://pytorch.org/docs/stable/generated/torch.nn.Module.html#torch.nn.Module

In [ ]:
#named_children 

#to iterate over the immediate modules of a model, yield both name of each child module and the module itself 

# useful to inspect or manipulate specifc submoduels ofa model by their naems